    [wso2.backoffice_service.datasourceConfiguration]
    description = "Database for admin"
    url = "jdbc:postgresql://10.102.56.192:5432/WSO2AM_DB"
    username = "wso2carbon"
    password = "wso2carbon"
    validationTimeout = 250
    testQuery = "SELECT 1"
    driver = "org.postgresql.Driver"
