{{- if and .Values.wso2.apk.helmHooks .Values.wso2.apk.helmHooks.webhooksCleanupEnabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "apk-helm.resource.prefix" . }}-apk-wso2-cleanup-webhooks"
  annotations:
    "helm.sh/hook": pre-install,pre-delete,pre-upgrade
    "helm.sh/hook-weight": "1"
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      serviceAccountName: "{{ template "apk-helm.resource.prefix" . }}-apk-wso2-cleanup-serviceaccount"
      containers:
      - name: cleanup
        image: "choreoanonymouspullable.azurecr.io/choreoipaas/kubectl:1.0.0"
        command:
          - "sh"
          - "-c"
          - |
            # Check and delete the mutating webhook configuration if it exists
            if kubectl get mutatingwebhookconfigurations "{{ template "apk-helm.resource.prefix" . }}-mutating-webhook-configuration" > /dev/null 2>&1; then
              kubectl delete mutatingwebhookconfigurations "{{ template "apk-helm.resource.prefix" . }}-mutating-webhook-configuration" || true
            else
              echo "Mutating webhook configuration not found."
            fi
            
            # Check and delete the validating webhook configuration if it exists
            if kubectl get validatingwebhookconfigurations "{{ template "apk-helm.resource.prefix" . }}-validating-webhook-configuration" > /dev/null 2>&1; then
              kubectl delete validatingwebhookconfigurations "{{ template "apk-helm.resource.prefix" . }}-validating-webhook-configuration" || true
            else
              echo "Validating webhook configuration not found."
            fi
            exit 0;
      restartPolicy: Never
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ template "apk-helm.resource.prefix" . }}-apk-wso2-webhook-cleanup-role"
  annotations:
    "helm.sh/hook": pre-install,pre-delete,pre-upgrade
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
  verbs: ["delete", "get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ template "apk-helm.resource.prefix" . }}-apk-wso2-cleanup-serviceaccount"
  annotations:
    "helm.sh/hook": pre-install,pre-delete,pre-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ template "apk-helm.resource.prefix" . }}-apk-wso2-webhook-cleanup-binding"
  annotations:
    "helm.sh/hook": pre-install,pre-delete,pre-upgrade
subjects:
- kind: ServiceAccount
  name: "{{ template "apk-helm.resource.prefix" . }}-apk-wso2-cleanup-serviceaccount"
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: "{{ template "apk-helm.resource.prefix" . }}-apk-wso2-webhook-cleanup-role"
  apiGroup: rbac.authorization.k8s.io
---
{{- end -}}
