[wso2.devportal_service.devportal]
DEVPORTAL_PORT = 9444


# Sample configurations
[wso2.devportal_service.devportal.datasourceConfiguration]
description = "Test"
url = "jdbc:postgresql://localhost:5432/APKDB"
username = "admin"
password = "admin"
validationTimeout = 30000
testQuery = "SELECT 1"


[wso2.devportal_service.devportal.throttleConfig]
enableUnlimitedTier = true

