// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/subscription/applicationmapping.proto

package org.wso2.apk.enforcer.discovery.subscription;

public final class ApplicationMappingProto {
  private ApplicationMappingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wso2_discovery_subscription_ApplicationMapping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wso2_discovery_subscription_ApplicationMapping_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4wso2/discovery/subscription/applicatio" +
      "nmapping.proto\022\033wso2.discovery.subscript" +
      "ion\"i\n\022ApplicationMapping\022\014\n\004uuid\030\001 \001(\t\022" +
      "\026\n\016applicationRef\030\002 \001(\t\022\027\n\017subscriptionR" +
      "ef\030\003 \001(\t\022\024\n\014organization\030\004 \001(\tB\233\001\n,org.w" +
      "so2.apk.enforcer.discovery.subscriptionB" +
      "\027ApplicationMappingProtoP\001ZPgithub.com/w" +
      "so2/apk/common-go-libs/pkg/discovery/api" +
      "/wso2/discovery/subscriptionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_wso2_discovery_subscription_ApplicationMapping_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wso2_discovery_subscription_ApplicationMapping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wso2_discovery_subscription_ApplicationMapping_descriptor,
        new java.lang.String[] { "Uuid", "ApplicationRef", "SubscriptionRef", "Organization", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
