// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/subscription/application_key_mapping.proto

package org.wso2.apk.enforcer.discovery.subscription;

/**
 * <pre>
 * ApplicationKeyMapping data model
 * </pre>
 *
 * Protobuf type {@code wso2.discovery.subscription.ApplicationKeyMapping}
 */
public final class ApplicationKeyMapping extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wso2.discovery.subscription.ApplicationKeyMapping)
    ApplicationKeyMappingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ApplicationKeyMapping.newBuilder() to construct.
  private ApplicationKeyMapping(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ApplicationKeyMapping() {
    applicationUUID_ = "";
    securityScheme_ = "";
    applicationIdentifier_ = "";
    keyType_ = "";
    envID_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ApplicationKeyMapping();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ApplicationKeyMapping(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            applicationUUID_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            securityScheme_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            applicationIdentifier_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            keyType_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            envID_ = s;
            break;
          }
          case 48: {

            timestamp_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMappingProto.internal_static_wso2_discovery_subscription_ApplicationKeyMapping_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMappingProto.internal_static_wso2_discovery_subscription_ApplicationKeyMapping_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping.class, org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping.Builder.class);
  }

  public static final int APPLICATIONUUID_FIELD_NUMBER = 1;
  private volatile java.lang.Object applicationUUID_;
  /**
   * <code>string applicationUUID = 1;</code>
   * @return The applicationUUID.
   */
  @java.lang.Override
  public java.lang.String getApplicationUUID() {
    java.lang.Object ref = applicationUUID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      applicationUUID_ = s;
      return s;
    }
  }
  /**
   * <code>string applicationUUID = 1;</code>
   * @return The bytes for applicationUUID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getApplicationUUIDBytes() {
    java.lang.Object ref = applicationUUID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      applicationUUID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECURITYSCHEME_FIELD_NUMBER = 2;
  private volatile java.lang.Object securityScheme_;
  /**
   * <code>string securityScheme = 2;</code>
   * @return The securityScheme.
   */
  @java.lang.Override
  public java.lang.String getSecurityScheme() {
    java.lang.Object ref = securityScheme_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      securityScheme_ = s;
      return s;
    }
  }
  /**
   * <code>string securityScheme = 2;</code>
   * @return The bytes for securityScheme.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSecuritySchemeBytes() {
    java.lang.Object ref = securityScheme_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      securityScheme_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPLICATIONIDENTIFIER_FIELD_NUMBER = 3;
  private volatile java.lang.Object applicationIdentifier_;
  /**
   * <code>string applicationIdentifier = 3;</code>
   * @return The applicationIdentifier.
   */
  @java.lang.Override
  public java.lang.String getApplicationIdentifier() {
    java.lang.Object ref = applicationIdentifier_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      applicationIdentifier_ = s;
      return s;
    }
  }
  /**
   * <code>string applicationIdentifier = 3;</code>
   * @return The bytes for applicationIdentifier.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getApplicationIdentifierBytes() {
    java.lang.Object ref = applicationIdentifier_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      applicationIdentifier_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEYTYPE_FIELD_NUMBER = 4;
  private volatile java.lang.Object keyType_;
  /**
   * <code>string keyType = 4;</code>
   * @return The keyType.
   */
  @java.lang.Override
  public java.lang.String getKeyType() {
    java.lang.Object ref = keyType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      keyType_ = s;
      return s;
    }
  }
  /**
   * <code>string keyType = 4;</code>
   * @return The bytes for keyType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyTypeBytes() {
    java.lang.Object ref = keyType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      keyType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENVID_FIELD_NUMBER = 5;
  private volatile java.lang.Object envID_;
  /**
   * <code>string envID = 5;</code>
   * @return The envID.
   */
  @java.lang.Override
  public java.lang.String getEnvID() {
    java.lang.Object ref = envID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      envID_ = s;
      return s;
    }
  }
  /**
   * <code>string envID = 5;</code>
   * @return The bytes for envID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEnvIDBytes() {
    java.lang.Object ref = envID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      envID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getApplicationUUIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, applicationUUID_);
    }
    if (!getSecuritySchemeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, securityScheme_);
    }
    if (!getApplicationIdentifierBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, applicationIdentifier_);
    }
    if (!getKeyTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, keyType_);
    }
    if (!getEnvIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, envID_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(6, timestamp_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getApplicationUUIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, applicationUUID_);
    }
    if (!getSecuritySchemeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, securityScheme_);
    }
    if (!getApplicationIdentifierBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, applicationIdentifier_);
    }
    if (!getKeyTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, keyType_);
    }
    if (!getEnvIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, envID_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, timestamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping)) {
      return super.equals(obj);
    }
    org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping other = (org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping) obj;

    if (!getApplicationUUID()
        .equals(other.getApplicationUUID())) return false;
    if (!getSecurityScheme()
        .equals(other.getSecurityScheme())) return false;
    if (!getApplicationIdentifier()
        .equals(other.getApplicationIdentifier())) return false;
    if (!getKeyType()
        .equals(other.getKeyType())) return false;
    if (!getEnvID()
        .equals(other.getEnvID())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + APPLICATIONUUID_FIELD_NUMBER;
    hash = (53 * hash) + getApplicationUUID().hashCode();
    hash = (37 * hash) + SECURITYSCHEME_FIELD_NUMBER;
    hash = (53 * hash) + getSecurityScheme().hashCode();
    hash = (37 * hash) + APPLICATIONIDENTIFIER_FIELD_NUMBER;
    hash = (53 * hash) + getApplicationIdentifier().hashCode();
    hash = (37 * hash) + KEYTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getKeyType().hashCode();
    hash = (37 * hash) + ENVID_FIELD_NUMBER;
    hash = (53 * hash) + getEnvID().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ApplicationKeyMapping data model
   * </pre>
   *
   * Protobuf type {@code wso2.discovery.subscription.ApplicationKeyMapping}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wso2.discovery.subscription.ApplicationKeyMapping)
      org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMappingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMappingProto.internal_static_wso2_discovery_subscription_ApplicationKeyMapping_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMappingProto.internal_static_wso2_discovery_subscription_ApplicationKeyMapping_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping.class, org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping.Builder.class);
    }

    // Construct using org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      applicationUUID_ = "";

      securityScheme_ = "";

      applicationIdentifier_ = "";

      keyType_ = "";

      envID_ = "";

      timestamp_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMappingProto.internal_static_wso2_discovery_subscription_ApplicationKeyMapping_descriptor;
    }

    @java.lang.Override
    public org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping getDefaultInstanceForType() {
      return org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping.getDefaultInstance();
    }

    @java.lang.Override
    public org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping build() {
      org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping buildPartial() {
      org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping result = new org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping(this);
      result.applicationUUID_ = applicationUUID_;
      result.securityScheme_ = securityScheme_;
      result.applicationIdentifier_ = applicationIdentifier_;
      result.keyType_ = keyType_;
      result.envID_ = envID_;
      result.timestamp_ = timestamp_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping) {
        return mergeFrom((org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping other) {
      if (other == org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping.getDefaultInstance()) return this;
      if (!other.getApplicationUUID().isEmpty()) {
        applicationUUID_ = other.applicationUUID_;
        onChanged();
      }
      if (!other.getSecurityScheme().isEmpty()) {
        securityScheme_ = other.securityScheme_;
        onChanged();
      }
      if (!other.getApplicationIdentifier().isEmpty()) {
        applicationIdentifier_ = other.applicationIdentifier_;
        onChanged();
      }
      if (!other.getKeyType().isEmpty()) {
        keyType_ = other.keyType_;
        onChanged();
      }
      if (!other.getEnvID().isEmpty()) {
        envID_ = other.envID_;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object applicationUUID_ = "";
    /**
     * <code>string applicationUUID = 1;</code>
     * @return The applicationUUID.
     */
    public java.lang.String getApplicationUUID() {
      java.lang.Object ref = applicationUUID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        applicationUUID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string applicationUUID = 1;</code>
     * @return The bytes for applicationUUID.
     */
    public com.google.protobuf.ByteString
        getApplicationUUIDBytes() {
      java.lang.Object ref = applicationUUID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        applicationUUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string applicationUUID = 1;</code>
     * @param value The applicationUUID to set.
     * @return This builder for chaining.
     */
    public Builder setApplicationUUID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      applicationUUID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string applicationUUID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearApplicationUUID() {
      
      applicationUUID_ = getDefaultInstance().getApplicationUUID();
      onChanged();
      return this;
    }
    /**
     * <code>string applicationUUID = 1;</code>
     * @param value The bytes for applicationUUID to set.
     * @return This builder for chaining.
     */
    public Builder setApplicationUUIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      applicationUUID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object securityScheme_ = "";
    /**
     * <code>string securityScheme = 2;</code>
     * @return The securityScheme.
     */
    public java.lang.String getSecurityScheme() {
      java.lang.Object ref = securityScheme_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        securityScheme_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string securityScheme = 2;</code>
     * @return The bytes for securityScheme.
     */
    public com.google.protobuf.ByteString
        getSecuritySchemeBytes() {
      java.lang.Object ref = securityScheme_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        securityScheme_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string securityScheme = 2;</code>
     * @param value The securityScheme to set.
     * @return This builder for chaining.
     */
    public Builder setSecurityScheme(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      securityScheme_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string securityScheme = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSecurityScheme() {
      
      securityScheme_ = getDefaultInstance().getSecurityScheme();
      onChanged();
      return this;
    }
    /**
     * <code>string securityScheme = 2;</code>
     * @param value The bytes for securityScheme to set.
     * @return This builder for chaining.
     */
    public Builder setSecuritySchemeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      securityScheme_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object applicationIdentifier_ = "";
    /**
     * <code>string applicationIdentifier = 3;</code>
     * @return The applicationIdentifier.
     */
    public java.lang.String getApplicationIdentifier() {
      java.lang.Object ref = applicationIdentifier_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        applicationIdentifier_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string applicationIdentifier = 3;</code>
     * @return The bytes for applicationIdentifier.
     */
    public com.google.protobuf.ByteString
        getApplicationIdentifierBytes() {
      java.lang.Object ref = applicationIdentifier_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        applicationIdentifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string applicationIdentifier = 3;</code>
     * @param value The applicationIdentifier to set.
     * @return This builder for chaining.
     */
    public Builder setApplicationIdentifier(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      applicationIdentifier_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string applicationIdentifier = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearApplicationIdentifier() {
      
      applicationIdentifier_ = getDefaultInstance().getApplicationIdentifier();
      onChanged();
      return this;
    }
    /**
     * <code>string applicationIdentifier = 3;</code>
     * @param value The bytes for applicationIdentifier to set.
     * @return This builder for chaining.
     */
    public Builder setApplicationIdentifierBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      applicationIdentifier_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object keyType_ = "";
    /**
     * <code>string keyType = 4;</code>
     * @return The keyType.
     */
    public java.lang.String getKeyType() {
      java.lang.Object ref = keyType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string keyType = 4;</code>
     * @return The bytes for keyType.
     */
    public com.google.protobuf.ByteString
        getKeyTypeBytes() {
      java.lang.Object ref = keyType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string keyType = 4;</code>
     * @param value The keyType to set.
     * @return This builder for chaining.
     */
    public Builder setKeyType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      keyType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string keyType = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyType() {
      
      keyType_ = getDefaultInstance().getKeyType();
      onChanged();
      return this;
    }
    /**
     * <code>string keyType = 4;</code>
     * @param value The bytes for keyType to set.
     * @return This builder for chaining.
     */
    public Builder setKeyTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      keyType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object envID_ = "";
    /**
     * <code>string envID = 5;</code>
     * @return The envID.
     */
    public java.lang.String getEnvID() {
      java.lang.Object ref = envID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        envID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string envID = 5;</code>
     * @return The bytes for envID.
     */
    public com.google.protobuf.ByteString
        getEnvIDBytes() {
      java.lang.Object ref = envID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        envID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string envID = 5;</code>
     * @param value The envID to set.
     * @return This builder for chaining.
     */
    public Builder setEnvID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      envID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string envID = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnvID() {
      
      envID_ = getDefaultInstance().getEnvID();
      onChanged();
      return this;
    }
    /**
     * <code>string envID = 5;</code>
     * @param value The bytes for envID to set.
     * @return This builder for chaining.
     */
    public Builder setEnvIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      envID_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wso2.discovery.subscription.ApplicationKeyMapping)
  }

  // @@protoc_insertion_point(class_scope:wso2.discovery.subscription.ApplicationKeyMapping)
  private static final org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping();
  }

  public static org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ApplicationKeyMapping>
      PARSER = new com.google.protobuf.AbstractParser<ApplicationKeyMapping>() {
    @java.lang.Override
    public ApplicationKeyMapping parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ApplicationKeyMapping(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ApplicationKeyMapping> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ApplicationKeyMapping> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.wso2.apk.enforcer.discovery.subscription.ApplicationKeyMapping getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

