// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/subscription/application.proto

package org.wso2.apk.enforcer.discovery.subscription;

public final class ApplicationProto {
  private ApplicationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wso2_discovery_subscription_Application_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wso2_discovery_subscription_Application_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wso2_discovery_subscription_Application_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wso2_discovery_subscription_Application_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wso2_discovery_subscription_Application_Key_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wso2_discovery_subscription_Application_Key_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-wso2/discovery/subscription/applicatio" +
      "n.proto\022\033wso2.discovery.subscription\"\347\002\n" +
      "\013Application\022\017\n\007eventId\030\001 \001(\t\022\014\n\004name\030\002 " +
      "\001(\t\022\014\n\004uuid\030\003 \001(\t\022\r\n\005owner\030\004 \001(\t\022\016\n\006poli" +
      "cy\030\005 \001(\t\022L\n\nattributes\030\006 \003(\01328.wso2.disc" +
      "overy.subscription.Application.Attribute" +
      "sEntry\022:\n\004keys\030\007 \003(\0132,.wso2.discovery.su" +
      "bscription.Application.Key\022\024\n\014organizati" +
      "on\030\010 \001(\t\022\021\n\ttimeStamp\030\t \001(\t\0321\n\017Attribute" +
      "sEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032&" +
      "\n\003Key\022\013\n\003key\030\001 \001(\t\022\022\n\nkeyManager\030\002 \001(\tB\223" +
      "\001\n,org.wso2.apk.enforcer.discovery.subsc" +
      "riptionB\020ApplicationProtoP\001ZOgithub.com/" +
      "envoyproxy/go-control-plane/wso2/discove" +
      "ry/subscription;subscriptionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_wso2_discovery_subscription_Application_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wso2_discovery_subscription_Application_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wso2_discovery_subscription_Application_descriptor,
        new java.lang.String[] { "EventId", "Name", "Uuid", "Owner", "Policy", "Attributes", "Keys", "Organization", "TimeStamp", });
    internal_static_wso2_discovery_subscription_Application_AttributesEntry_descriptor =
      internal_static_wso2_discovery_subscription_Application_descriptor.getNestedTypes().get(0);
    internal_static_wso2_discovery_subscription_Application_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wso2_discovery_subscription_Application_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_wso2_discovery_subscription_Application_Key_descriptor =
      internal_static_wso2_discovery_subscription_Application_descriptor.getNestedTypes().get(1);
    internal_static_wso2_discovery_subscription_Application_Key_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wso2_discovery_subscription_Application_Key_descriptor,
        new java.lang.String[] { "Key", "KeyManager", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
