// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/subscription/application.proto

package org.wso2.apk.enforcer.discovery.subscription;

public interface EnvironmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wso2.discovery.subscription.Environment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string envID = 1;</code>
   * @return The envID.
   */
  java.lang.String getEnvID();
  /**
   * <code>string envID = 1;</code>
   * @return The bytes for envID.
   */
  com.google.protobuf.ByteString
      getEnvIDBytes();

  /**
   * <code>string applicationIdentifier = 2;</code>
   * @return The applicationIdentifier.
   */
  java.lang.String getApplicationIdentifier();
  /**
   * <code>string applicationIdentifier = 2;</code>
   * @return The bytes for applicationIdentifier.
   */
  com.google.protobuf.ByteString
      getApplicationIdentifierBytes();

  /**
   * <code>string keyType = 3;</code>
   * @return The keyType.
   */
  java.lang.String getKeyType();
  /**
   * <code>string keyType = 3;</code>
   * @return The bytes for keyType.
   */
  com.google.protobuf.ByteString
      getKeyTypeBytes();
}
