// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/subscription/subscription.proto

package org.wso2.apk.enforcer.discovery.subscription;

public final class SubscriptionProto {
  private SubscriptionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wso2_discovery_subscription_Subscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wso2_discovery_subscription_Subscription_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.wso2/discovery/subscription/subscripti" +
      "on.proto\022\033wso2.discovery.subscription\"\267\001" +
      "\n\014Subscription\022\017\n\007eventId\030\001 \001(\t\022\026\n\016appli" +
      "cationRef\030\002 \001(\t\022\016\n\006apiRef\030\003 \001(\t\022\020\n\010polic" +
      "yId\030\004 \001(\t\022\021\n\tsubStatus\030\005 \001(\t\022\022\n\nsubscrib" +
      "er\030\006 \001(\t\022\014\n\004uuid\030\007 \001(\t\022\021\n\ttimeStamp\030\010 \001(" +
      "\t\022\024\n\014organization\030\t \001(\tB\224\001\n,org.wso2.apk" +
      ".enforcer.discovery.subscriptionB\021Subscr" +
      "iptionProtoP\001ZOgithub.com/envoyproxy/go-" +
      "control-plane/wso2/discovery/subscriptio" +
      "n;subscriptionb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_wso2_discovery_subscription_Subscription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wso2_discovery_subscription_Subscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wso2_discovery_subscription_Subscription_descriptor,
        new java.lang.String[] { "EventId", "ApplicationRef", "ApiRef", "PolicyId", "SubStatus", "Subscriber", "Uuid", "TimeStamp", "Organization", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
