// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/subscription/subscription.proto

package org.wso2.apk.enforcer.discovery.subscription;

public final class SubscriptionProto {
  private SubscriptionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wso2_discovery_subscription_Subscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wso2_discovery_subscription_Subscription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wso2_discovery_subscription_SubscribedAPI_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wso2_discovery_subscription_SubscribedAPI_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.wso2/discovery/subscription/subscripti" +
      "on.proto\022\033wso2.discovery.subscription\"\237\001" +
      "\n\014Subscription\022\021\n\tsubStatus\030\001 \001(\t\022\014\n\004uui" +
      "d\030\002 \001(\t\022\024\n\014organization\030\003 \001(\t\022A\n\rsubscri" +
      "bedApi\030\004 \001(\0132*.wso2.discovery.subscripti" +
      "on.SubscribedAPI\022\025\n\rratelimitTier\030\005 \001(\t\"" +
      ".\n\rSubscribedAPI\022\014\n\004name\030\001 \001(\t\022\017\n\007versio" +
      "n\030\002 \001(\tB\225\001\n,org.wso2.apk.enforcer.discov" +
      "ery.subscriptionB\021SubscriptionProtoP\001ZPg" +
      "ithub.com/wso2/apk/common-go-libs/pkg/di" +
      "scovery/api/wso2/discovery/subscriptionb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_wso2_discovery_subscription_Subscription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wso2_discovery_subscription_Subscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wso2_discovery_subscription_Subscription_descriptor,
        new java.lang.String[] { "SubStatus", "Uuid", "Organization", "SubscribedApi", "RatelimitTier", });
    internal_static_wso2_discovery_subscription_SubscribedAPI_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wso2_discovery_subscription_SubscribedAPI_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wso2_discovery_subscription_SubscribedAPI_descriptor,
        new java.lang.String[] { "Name", "Version", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
