codecov:
  max_report_age: off

coverage:

  status:
    project: off
    patch: off
fixes:
  - "apk-repo/::"
flag_management:
  individual_flags:
    - name: adapter
      paths:
        - '**/adapter/**'
    - name: admin-domain-service
      paths:
        - '**/admin/admin-domain-service/**'
    - name: backoffice-domain-service
      paths:
        - '**/backoffice/backoffice-domain-service/**'
    - name: devportal-domain-service
      paths:
        - '**/devportal/devportal-domain-service/**'
    - name: management-server
      paths:
        - '**/management-server/**'
    - name: runtime-domain-service
      paths:
        - '**/runtime-domain-service/**'
    - name: idp-domain-service
      paths:
        - '**/idp/idp-domain-service/**'
    - name: idp-ui
      paths:
        - '**/idp/idp-ui/**'

      statuses:
        - type: project
          target: 75%
          threshold: 1%
      carryforward: true
