# Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

{{- if .Values.wso2.apk.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "apk-helm.resource.prefix" . }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  secretObjects:
    - secretName: {{ template "apk-helm.resource.prefix" . }}-secrets
      type: Opaque
      data:
        - objectName: ratelimiter_redis_credentials
          key: ratelimiter_redis_credentials
    - secretName: {{ template "apk-helm.resource.prefix" . }}-system-listener-tls
      type: Opaque
      data:
        - objectName: system-api-listener.key
          key: tls.key
        - objectName: system-api-listener.crt
          key: tls.crt
    - secretName: {{ template "apk-helm.resource.prefix" . }}-router-tls
      type: Opaque
      data:
        - objectName: router.key
          key: tls.key
        - objectName: router.crt
          key: tls.crt
  parameters:
    vaultAddress: {{ .Values.wso2.apk.secretProviderClass.vault.url }}
    roleName: {{ .Values.wso2.apk.secretProviderClass.vault.roleName }}
    objects: |
      - objectName: ratelimiter_redis_credentials
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.ratelimiterRedisCredentials.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.ratelimiterRedisCredentials.path | quote }}
      - objectName: adapter.key
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.adapterKey.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.adapterKey.path | quote }}
      - objectName: adapter.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.adapterCert.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.adapterCert.path | quote }}
      - objectName: adapter-ca.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.adapterCaCert.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.adapterCaCert.path | quote }}
      - objectName: enforcer.key
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerKey.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerKey.path | quote }}
      - objectName: enforcer.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerCert.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerCert.path | quote }}
      - objectName: enforcer-ca.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerCaCert.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerCaCert.path | quote }}
      - objectName: router.key
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.routerKey.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.routerKey.path | quote }}
      - objectName: router.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.routerCert.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.routerCert.path | quote }}
      - objectName: router-ca.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.routerCaCert.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.routerCaCert.path | quote }}
      - objectName: ratelimiter.key
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.ratelimiterKey.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.ratelimiterKey.path | quote }}
      - objectName: ratelimiter.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.ratelimiterCert.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.ratelimiterCert.path | quote }}
      - objectName: ratelimiter-ca.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.ratelimiterCaCert.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.ratelimiterCaCert.path | quote }}
      - objectName: commoncontroller.key
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.commonControllerKey.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.commonControllerKey.path | quote }}
      - objectName: commoncontroller.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.commonControllerCert.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.commonControllerCert.path | quote }}
      - objectName: commoncontroller-ca.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.commonControllerCaCert.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.commonControllerCaCert.path | quote }}
      - objectName: system-api-listener.key
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.systemApiListenerKey.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.systemApiListenerKey.path | quote }}
      - objectName: system-api-listener.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.systemApiListenerCert.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.systemApiListenerCert.path | quote }}
      - objectName: enforcer-jwks.key
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerJwksKey.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerJwksKey.path | quote }}
      - objectName: enforcer-jwks.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerJwksCert.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerJwksCert.path | quote }}
      - objectName: enforcer-jwks-ca.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerJwksCaCert.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.enforcerJwksCaCert.path | quote }}
{{ if and .Values.wso2.apk.dp.gatewayRuntime.tracing .Values.wso2.apk.dp.gatewayRuntime.tracing.enabled .Values.wso2.apk.dp.gatewayRuntime.tracing.configProperties .Values.wso2.apk.dp.gatewayRuntime.tracing.configProperties.tls .Values.wso2.apk.dp.gatewayRuntime.tracing.configProperties.tls.enabled }}
      - objectName: tracing-ca.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.tracingCaCert.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.tracingCaCert.path | quote }}
      - objectName: tracing.crt
        secretKey: {{ .Values.wso2.apk.secretProviderClass.secrets.tracingCert.key | quote }}
        secretPath: {{ .Values.wso2.apk.secretProviderClass.secrets.tracingCert.path | quote }}
{{- end }}
{{- end }}
