apiVersion: v2
name: apk-helm
description: A Helm chart for APK components
type: application
version: 1.2.0-m1
appVersion: "1.16.0"
dependencies:
  - name: postgresql
    version: "15.5.24"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.8.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: cert-manager
    version: "v1.10.2"
    repository: "https://charts.jetstack.io"
    condition: certmanager.enabled
