apiVersion: v2
name: kubernetes-gateway-helm
description: A Helm umbrella chart that installs my-app and Envoy Gateway
type: application
version: 2.0.0-alpha2
appVersion: "2.0.0-alpha2"
dependencies:
  - name: gateway-helm
    version: "1.5.0"
    repository: "oci://docker.io/envoyproxy"
    alias: envoy     # optional, gives it a nicer sub-chart name
    condition: envoy.enabled # optional: only pull if values.envoy.enabled == true
  - name: postgresql
    version: "16.4.14"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "20.10.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: cert-manager
    version: "v1.17.1"
    repository: "https://charts.jetstack.io"
    condition: certmanager.enabled
