apiVersion: v2
name: choreo-apk
description: A Helm chart for APK components
type: application
version: 1.3.0-4
appVersion: "1.3.0"
dependencies:
  - name: postgresql
    version: "16.4.14"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "20.10.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
