apiVersion: v2
name: apk-helm
description: A Helm chart for APK components
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: postgresql
    version: "11.9.6"
    repository: "https://charts.bitnami.com/bitnami"
    condition: wso2.apk.cp.database.enabled
  # - name: ipk
  #   version: "6.0.0-1"
  #   repository: "http://localhost:8080"
  #   condition: wso2.apk.cp.ipk.enabled
