# Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
{{- if .Values.wso2.apk.cp.enabled }}
apiVersion: "gateway.networking.k8s.io/v1beta1"
kind: "HTTPRoute"
metadata:
  name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-httproute
  namespace: {{ .Release.Namespace }}
  labels:
    api-name: "backoffice-domain-service"
    api-version: "1.0.0"
spec:
  hostnames:
  - "api.am.wso2.com"
  rules:
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)"
      method: "PUT"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/definition"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/definition"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/resource-paths"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/resource-paths"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/thumbnail"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/thumbnail"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/thumbnail"
      method: "PUT"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/thumbnail"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/documents"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/documents"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/documents"
      method: "POST"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/documents"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/documents/(.*)"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/documents/\\2"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/documents/(.*)"
      method: "PUT"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/documents/\\2"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/documents/(.*)"
      method: "DELETE"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/documents/\\2"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/documents/(.*)/content"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/documents/\\2/content"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/documents/(.*)/content"
      method: "POST"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/documents/\\2/content"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/comments"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/comments"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/comments"
      method: "POST"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/comments"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/comments/(.*)"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/comments/\\2"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/comments/(.*)"
      method: "DELETE"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/comments/\\2"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/comments/(.*)"
      method: "PATCH"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/comments/\\2"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/comments/(.*)/replies"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/comments/\\2/replies"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/subscriptions"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/subscriptions"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/subscriptions/(.*)/subscriber-info"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/subscriptions/\\1/subscriber-info"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/subscriptions/block-subscription"
      method: "POST"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/subscriptions/block-subscription"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/subscriptions/unblock-subscription"
      method: "POST"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/subscriptions/unblock-subscription"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/usage-plans"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/usage-plans"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/search"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/search"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/settings"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/settings"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/api-categories"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/api-categories"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/change-lifecycle"
      method: "POST"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/change-lifecycle"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/lifecycle-history"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/lifecycle-history"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/api/am/backoffice/apis/(.*)/lifecycle-state"
      method: "GET"
    filters:
    - type: "URLRewrite"
      urlRewrite:
        path:
          type: "ReplaceFullPath"
          replaceFullPath: "/api/am/backoffice/apis/\\1/lifecycle-state"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-backoffice-ds-backend
  parentRefs:
  - group: "gateway.networking.k8s.io"
    kind: "Gateway"
    name: "default"
    sectionName: "apilistener"
{{- end -}}
