// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: student_default_version.proto

package student_default_version

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StudentService_GetStudent_FullMethodName              = "/dineth.grpc.api.student.StudentService/GetStudent"
	StudentService_GetStudentStream_FullMethodName        = "/dineth.grpc.api.student.StudentService/GetStudentStream"
	StudentService_SendStudentStream_FullMethodName       = "/dineth.grpc.api.student.StudentService/SendStudentStream"
	StudentService_SendAndGetStudentStream_FullMethodName = "/dineth.grpc.api.student.StudentService/SendAndGetStudentStream"
)

// StudentServiceClient is the client API for StudentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudentServiceClient interface {
	GetStudent(ctx context.Context, in *StudentRequest, opts ...grpc.CallOption) (*StudentResponse, error)
	GetStudentStream(ctx context.Context, in *StudentRequest, opts ...grpc.CallOption) (StudentService_GetStudentStreamClient, error)
	SendStudentStream(ctx context.Context, opts ...grpc.CallOption) (StudentService_SendStudentStreamClient, error)
	SendAndGetStudentStream(ctx context.Context, opts ...grpc.CallOption) (StudentService_SendAndGetStudentStreamClient, error)
}

type studentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentServiceClient(cc grpc.ClientConnInterface) StudentServiceClient {
	return &studentServiceClient{cc}
}

func (c *studentServiceClient) GetStudent(ctx context.Context, in *StudentRequest, opts ...grpc.CallOption) (*StudentResponse, error) {
	out := new(StudentResponse)
	err := c.cc.Invoke(ctx, StudentService_GetStudent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) GetStudentStream(ctx context.Context, in *StudentRequest, opts ...grpc.CallOption) (StudentService_GetStudentStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StudentService_ServiceDesc.Streams[0], StudentService_GetStudentStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &studentServiceGetStudentStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StudentService_GetStudentStreamClient interface {
	Recv() (*StudentResponse, error)
	grpc.ClientStream
}

type studentServiceGetStudentStreamClient struct {
	grpc.ClientStream
}

func (x *studentServiceGetStudentStreamClient) Recv() (*StudentResponse, error) {
	m := new(StudentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *studentServiceClient) SendStudentStream(ctx context.Context, opts ...grpc.CallOption) (StudentService_SendStudentStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StudentService_ServiceDesc.Streams[1], StudentService_SendStudentStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &studentServiceSendStudentStreamClient{stream}
	return x, nil
}

type StudentService_SendStudentStreamClient interface {
	Send(*StudentRequest) error
	CloseAndRecv() (*StudentResponse, error)
	grpc.ClientStream
}

type studentServiceSendStudentStreamClient struct {
	grpc.ClientStream
}

func (x *studentServiceSendStudentStreamClient) Send(m *StudentRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *studentServiceSendStudentStreamClient) CloseAndRecv() (*StudentResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StudentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *studentServiceClient) SendAndGetStudentStream(ctx context.Context, opts ...grpc.CallOption) (StudentService_SendAndGetStudentStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &StudentService_ServiceDesc.Streams[2], StudentService_SendAndGetStudentStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &studentServiceSendAndGetStudentStreamClient{stream}
	return x, nil
}

type StudentService_SendAndGetStudentStreamClient interface {
	Send(*StudentRequest) error
	Recv() (*StudentResponse, error)
	grpc.ClientStream
}

type studentServiceSendAndGetStudentStreamClient struct {
	grpc.ClientStream
}

func (x *studentServiceSendAndGetStudentStreamClient) Send(m *StudentRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *studentServiceSendAndGetStudentStreamClient) Recv() (*StudentResponse, error) {
	m := new(StudentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StudentServiceServer is the server API for StudentService service.
// All implementations must embed UnimplementedStudentServiceServer
// for forward compatibility
type StudentServiceServer interface {
	GetStudent(context.Context, *StudentRequest) (*StudentResponse, error)
	GetStudentStream(*StudentRequest, StudentService_GetStudentStreamServer) error
	SendStudentStream(StudentService_SendStudentStreamServer) error
	SendAndGetStudentStream(StudentService_SendAndGetStudentStreamServer) error
	mustEmbedUnimplementedStudentServiceServer()
}

// UnimplementedStudentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStudentServiceServer struct {
}

func (UnimplementedStudentServiceServer) GetStudent(context.Context, *StudentRequest) (*StudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudent not implemented")
}
func (UnimplementedStudentServiceServer) GetStudentStream(*StudentRequest, StudentService_GetStudentStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStudentStream not implemented")
}
func (UnimplementedStudentServiceServer) SendStudentStream(StudentService_SendStudentStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SendStudentStream not implemented")
}
func (UnimplementedStudentServiceServer) SendAndGetStudentStream(StudentService_SendAndGetStudentStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SendAndGetStudentStream not implemented")
}
func (UnimplementedStudentServiceServer) mustEmbedUnimplementedStudentServiceServer() {}

// UnsafeStudentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudentServiceServer will
// result in compilation errors.
type UnsafeStudentServiceServer interface {
	mustEmbedUnimplementedStudentServiceServer()
}

func RegisterStudentServiceServer(s grpc.ServiceRegistrar, srv StudentServiceServer) {
	s.RegisterService(&StudentService_ServiceDesc, srv)
}

func _StudentService_GetStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).GetStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudentService_GetStudent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).GetStudent(ctx, req.(*StudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_GetStudentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StudentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StudentServiceServer).GetStudentStream(m, &studentServiceGetStudentStreamServer{stream})
}

type StudentService_GetStudentStreamServer interface {
	Send(*StudentResponse) error
	grpc.ServerStream
}

type studentServiceGetStudentStreamServer struct {
	grpc.ServerStream
}

func (x *studentServiceGetStudentStreamServer) Send(m *StudentResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StudentService_SendStudentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StudentServiceServer).SendStudentStream(&studentServiceSendStudentStreamServer{stream})
}

type StudentService_SendStudentStreamServer interface {
	SendAndClose(*StudentResponse) error
	Recv() (*StudentRequest, error)
	grpc.ServerStream
}

type studentServiceSendStudentStreamServer struct {
	grpc.ServerStream
}

func (x *studentServiceSendStudentStreamServer) SendAndClose(m *StudentResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *studentServiceSendStudentStreamServer) Recv() (*StudentRequest, error) {
	m := new(StudentRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StudentService_SendAndGetStudentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StudentServiceServer).SendAndGetStudentStream(&studentServiceSendAndGetStudentStreamServer{stream})
}

type StudentService_SendAndGetStudentStreamServer interface {
	Send(*StudentResponse) error
	Recv() (*StudentRequest, error)
	grpc.ServerStream
}

type studentServiceSendAndGetStudentStreamServer struct {
	grpc.ServerStream
}

func (x *studentServiceSendAndGetStudentStreamServer) Send(m *StudentResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *studentServiceSendAndGetStudentStreamServer) Recv() (*StudentRequest, error) {
	m := new(StudentRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StudentService_ServiceDesc is the grpc.ServiceDesc for StudentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dineth.grpc.api.student.StudentService",
	HandlerType: (*StudentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudent",
			Handler:    _StudentService_GetStudent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStudentStream",
			Handler:       _StudentService_GetStudentStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendStudentStream",
			Handler:       _StudentService_SendStudentStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SendAndGetStudentStream",
			Handler:       _StudentService_SendAndGetStudentStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "student_default_version.proto",
}