// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/config/enforcer/analytics_publisher.proto

package org.wso2.apk.enforcer.discovery.config.enforcer;

public final class AnalyticsPublisherProto {
  private AnalyticsPublisherProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wso2_discovery_config_enforcer_AnalyticsPublisher_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wso2_discovery_config_enforcer_AnalyticsPublisher_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wso2_discovery_config_enforcer_AnalyticsPublisher_ConfigPropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wso2_discovery_config_enforcer_AnalyticsPublisher_ConfigPropertiesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8wso2/discovery/config/enforcer/analyti" +
      "cs_publisher.proto\022\036wso2.discovery.confi" +
      "g.enforcer\"\320\001\n\022AnalyticsPublisher\022\017\n\007ena" +
      "bled\030\001 \001(\010\022b\n\020configProperties\030\002 \003(\0132H.w" +
      "so2.discovery.config.enforcer.AnalyticsP" +
      "ublisher.ConfigPropertiesEntry\022\014\n\004type\030\003" +
      " \001(\t\0327\n\025ConfigPropertiesEntry\022\013\n\003key\030\001 \001" +
      "(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\234\001\n/org.wso2.apk.e" +
      "nforcer.discovery.config.enforcerB\027Analy" +
      "ticsPublisherProtoP\001ZNgithub.com/envoypr" +
      "oxy/go-control-plane/wso2/discovery/conf" +
      "ig/enforcer;enforcerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_wso2_discovery_config_enforcer_AnalyticsPublisher_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wso2_discovery_config_enforcer_AnalyticsPublisher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wso2_discovery_config_enforcer_AnalyticsPublisher_descriptor,
        new java.lang.String[] { "Enabled", "ConfigProperties", "Type", });
    internal_static_wso2_discovery_config_enforcer_AnalyticsPublisher_ConfigPropertiesEntry_descriptor =
      internal_static_wso2_discovery_config_enforcer_AnalyticsPublisher_descriptor.getNestedTypes().get(0);
    internal_static_wso2_discovery_config_enforcer_AnalyticsPublisher_ConfigPropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wso2_discovery_config_enforcer_AnalyticsPublisher_ConfigPropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
