// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/config/enforcer/jwt_generator.proto

package org.wso2.apk.enforcer.discovery.config.enforcer;

public final class JWTGeneratorProto {
  private JWTGeneratorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wso2_discovery_config_enforcer_JWTGenerator_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wso2_discovery_config_enforcer_JWTGenerator_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wso2_discovery_config_enforcer_Keypair_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wso2_discovery_config_enforcer_Keypair_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2wso2/discovery/config/enforcer/jwt_gen" +
      "erator.proto\022\036wso2.discovery.config.enfo" +
      "rcer\"I\n\014JWTGenerator\0229\n\010keypairs\030\001 \003(\0132\'" +
      ".wso2.discovery.config.enforcer.Keypair\"" +
      "]\n\007Keypair\022\037\n\027public_certificate_path\030\001 " +
      "\001(\t\022\030\n\020private_key_path\030\002 \001(\t\022\027\n\017use_for" +
      "_signing\030\003 \001(\010B\226\001\n/org.wso2.apk.enforcer" +
      ".discovery.config.enforcerB\021JWTGenerator" +
      "ProtoP\001ZNgithub.com/envoyproxy/go-contro" +
      "l-plane/wso2/discovery/config/enforcer;e" +
      "nforcerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_wso2_discovery_config_enforcer_JWTGenerator_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wso2_discovery_config_enforcer_JWTGenerator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wso2_discovery_config_enforcer_JWTGenerator_descriptor,
        new java.lang.String[] { "Keypairs", });
    internal_static_wso2_discovery_config_enforcer_Keypair_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wso2_discovery_config_enforcer_Keypair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wso2_discovery_config_enforcer_Keypair_descriptor,
        new java.lang.String[] { "PublicCertificatePath", "PrivateKeyPath", "UseForSigning", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
