---
openapi: 3.0.1
info:
  title: WSO2 API Platform for Kubernetes - Deploy K8s Resource API
  description: |
    This API is used to generate K8s resources for an API.
  version: 1.0.0
paths:
  /apis/deploy:
    post:
      tags:
        - APIs
      summary: Deploy API
      description: | 
      operationId: deployAPI
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/deploy-api-body"
      responses:
        "201":
          description: |
            API deployed successfully
          headers:
            Location:
              description: |
                The URL of the newly created resource.
              style: simple
              explode: false
              schema:
                type: string
            Content-Type:
              description: |
                The content type of the body.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/yaml:
              schema:
                $ref: "./apk-conf-schema.yaml#/components/schemas/APKConf"
        "400":
          $ref: "./common-responses.yaml#/components/responses/BadRequest"

        "500":
          $ref: "./common-responses.yaml#/components/responses/InternalServerError"

  /apis/undeploy:
    post:
      tags:
        - APIs
      summary: Undeploy API
      description: | 
      operationId: undeployAPI
      parameters:
        - name: apiId
          in: query
          description: |
            UUID of the K8s API Resource
          required: true
          schema:
            type: string
      responses:
        "202":
          description: |
            API undeployed successfully
          headers:
            Content-Type:
              description: |
                The content type of the body.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                type: string
                example: "API undeployed successfully"
        "400":
          $ref: "./common-responses.yaml#/components/responses/BadRequest"

        "500":
          $ref: "./common-responses.yaml#/components/responses/InternalServerError"
  /apis/configurations:
    get:
      tags:
        - APIs
      summary: Get API Configurations
      description: | 
      operationId: getAPIConfigurations
      parameters:
        - name: apiId
          in: query
          description: |
            UUID of the K8s API Resource
          required: true
          schema:
            type: string
      responses:
        "200":
          description: |
            API configurations retrieved successfully
          headers:
            Content-Type:
              description: |
                The content type of the body.
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/yaml:
              schema:
                $ref: "./apk-conf-schema.yaml#/components/schemas/APKConf"
        "400":
          $ref: "./common-responses.yaml#/components/responses/BadRequest"
        "404":
          $ref: "./common-responses.yaml#/components/responses/NotFound"
        "500":
          $ref: "./common-responses.yaml#/components/responses/InternalServerError"
components:
  schemas:
    deploy-api-body:
      properties:
        apkConfiguration:
          type: string
          description: apk-configuration file
          format: binary
          example: "api.apk-conf"
        definitionFile:
          type: string
          description: api definition (OAS/Graphql/WebSocket)
          format: binary
          example: "openapi.yaml"
 
  parameters:
    apiId:
      name: apiId
      in: path
      description: |
        **API ID** consisting of the **Name** of the API.
      required: true
      style: simple
      explode: false
      schema:
        type: string
    organizationId:
      name: X-WSO2-Organization
      in: header
      description: |
        **Organization ID** of the organization the API belongs to.
      required: true
      style: simple
      explode: false
      schema:
        type: string
    Accept:
      name: Accept
      in: header
      description: |
        Media types acceptable for the response. Default is application/json.
      required: false
      style: simple
      explode: false
      schema:
        type: string
        default: application/json
