// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package org.wso2.apk.integration.utils.clients.studentGrpcClient;

public interface StudentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dineth.grpc.v1.student.StudentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();
}
