apiVersion: dp.wso2.com/v1alpha1
kind: APIPolicy
metadata:
  name: interceptor-api-policy-resource-level
spec:
  override:
    requestInterceptor:
      backendRef:
        name: interceptor-backend-v1
      includes:
        - request_body
        - request_headers
  targetRef:
    group: gateway.networking.k8s.io
    kind: Resource
    name: prod-http-route-http-bin-api-basic
