apiVersion: cp.wso2.com/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: application-sample
    app.kubernetes.io/part-of: test
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: test
  name: application-sample-2
spec:
  uuid: f46b39bf-2f22-4224-ae8b-bc295dcf9d78
  name: app2
  owner: Alice
  policy: 20PerMin
  organization: wso2 
  attributes: 
    attb3: value3
    attb4: value4
  consumerKeys:
    - key: hef14gh8syDvTtvoWYeIHYbjF_Ya
      keyManager: Resident Key Manager
  subscriptions:
    - uuid: ff041d1b-be19-4529-a861-86a79905a1ad
      name: sub1
      apiRef: SwaggerPetstore
      policyId: Unlimited
      subscriptionStatus: ACTIVE
      subscriber: Tom 
