#   Copyright (c) 2022, WSO2 LLC. (http://www.wso2.com).
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
################################################################################
openapi: 3.0.1
info:
  title: WSO2 API Platform for Kubernetes (APK) - Admin
  description: |
    This document specifies a **RESTful API** for WSO2 **API Platform for Kubernetes (APK)** - **Admin Portal**.
  contact:
    name: WSO2
    url: https://wso2.com/api-manager/
    email: architecture@wso2.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1
servers:
  - url: https://apis.wso2.com/api/am/admin/v1
paths:
  ######################################################
  # The "Content Search Results" Throttling Policies
  ######################################################
  /policies/search:
    get:
      tags:
        - Unified Search
      summary: |
        Retrieve/Search Policies
      description: |
        This operation provides you a list of available Policies qualifying the given keyword match.
      security:
        - OAuth2Security:
            - apk:admin
            - apk:tier_view
            - apk:policies_import_export
      operationId: policySearch

  ######################################################
  # The "Application Rate Plans Collection" resource API
  ######################################################
  /application-rate-plans:
    get:
      tags:
        - Application Rate Plan (Collection)
      summary: Get all Application Rate Plans
      description: |
        Retrieves all existing application rate plans.
      security:
        - OAuth2Security:
            - apk:tier_manage
      operationId: getApplicationRatePlans

    post:
      tags:
        - Application Rate Plan (Collection)
      summary: Add an Application Rate Plan
      description: |
        This operation can be used to add a new application level rate plan.
      security:
        - OAuth2Security:
            - apk:tier_manage
      operationId: addApplicationRatePlan

  ######################################################
  # The "Individual Application Rate Plan" resource API
  ######################################################
  /application-rate-plans/{planId}:
    get:
      tags:
        - Application Rate Plan (Individual)
      summary: Get an Application Rate Plan
      description: |
        Retrieves an application rate plan.
      security:
        - OAuth2Security:
            - apk:tier_manage
      operationId: getApplicationRatePlanById

    put:
      tags:
        - Application Rate Plan (Individual)
      summary: Update an Application Rate Plan
      description: |
        Updates an existing application level rate plan. Upon a successful update, you will receive the updated application plan as the response.
      security:
        - OAuth2Security:
            - apk:tier_manage
      operationId: updateApplicationRatePlan

    delete:
      tags:
        - Application Rate Plan (Individual)
      summary: Delete an Application Rate Plan
      description: |
        Deletes an application level rate plan.
      security:
        - OAuth2Security:
            - apk:tier_manage
      operationId: removeApplicationRatePlan


  ######################################################
  # The "Business Plans Collection" resource API
  ######################################################
  /business-plans:
    get:
      tags:
        - Business Plan (Collection)
      summary: Get all Business Plans
      description: |
        This operation can be used to retrieve all Business Plans.
      security:
        - OAuth2Security:
            - apk:tier_manage
      operationId: getAllBusinessPlans

    post:
      tags:
        -  Business Plan (Collection)
      summary: Add a Business Plan
      description: |
        This operation can be used to add a  Business Plan specifying the details of the plan in the payload.
      security:
        - OAuth2Security:
            - apk:tier_manage
      operationId: addBusinessPlan

  ######################################################
  # The "Individual Business Plan" resource API
  ######################################################
  /business-plans/{planId}:
    get:
      tags:
        - Business Plan (Individual)
      summary: Get a Business Plan
      description: |
        This operation can be used to retrieves Business Plan by specifying the Id of the plan as a path parameter
      security:
        - OAuth2Security:
            - apk:tier_manage
      operationId: getBusinessPlanById

    put:
      tags:
        - Business Plan (Individual)
      summary: Update a Business Plan
      description: |
        Updates an existing Business Plan.
      security:
        - OAuth2Security:
            - apk:tier_manage
      operationId: updateBusinessPlan

    delete:
      tags:
        - Business Plan (Individual)
      summary: Delete a Business Plan
      description: |
        This operation can be used to delete a business plan by specifying the Id of the plan as a path parameter.
      security:
        - OAuth2Security:
            - apk:tier_manage
      operationId: removeBusinessPlan

  ######################################################
  # "Export Throttling Policy" resource API
  ######################################################
  /throttling/policies/export:
    get:
      tags:
        - Import Export
      summary: Export a Throttling Policy
      description: |
        This operation can be used to export the details of a particular Throttling Policy.
      security:
        - OAuth2Security:
            - apk:tier_manage
      operationId: exportThrottlingPolicy
  ####################################################################
  # Import Throttling Policy
  ####################################################################
  /throttling/policies/import:
    post:
      tags:
        - Import Export
      summary: Import a Throttling Policy
      description: |
        This operation can be used to import a Throttling Policy.
      security:
        - OAuth2Security:
            - apk:tier_manage
      operationId: importThrottlingPolicy
  ######################################################
  # The "Deny Policy Collection" resource API
  ######################################################
  /deny-policies:
    get:
      tags:
        - Deny Policies (Collection)
      summary: Get all Deny Policies
      description: |
        Retrieves all existing deny policies.
      security:
        - OAuth2Security:
            - apk:bl_manage
      operationId: getAllDenyPolicies

    post:
      tags:
        - Deny Policies (Collection)
      summary: Add a deny policy
      description: |
        Adds a new deny policy
      security:
        - OAuth2Security:
            - apk:bl_manage
      operationId: addDenyPolicy

  ######################################################
  # The "Individual Deny Policy" resource API
  ######################################################
  /deny-policies/{policyId}:
    get:
      tags:
        - Deny Policy (Individual)
      summary: Get a Deny Policy
      description: |
        Retrieves a Deny policy providing the policy Id
      security:
        - OAuth2Security:
            - apk:bl_manage
      operationId: getDenyPolicyById

    delete:
      tags:
        - Deny Policy (Individual)
      summary: Delete a Deny Policy
      description: |
        Deletes an existing deny policy
      security:
        - OAuth2Security:
            - apk:bl_manage
      operationId: removeDenyPolicy

    patch:
      tags:
        - Deny Policy (Individual)
      summary: Update a Deny Policy
      description: |
        Update a deny policy by Id
      security:
        - OAuth2Security:
            - apk:bl_manage
      operationId: updateDenyPolicy

  ######################################################
  # The "Application Collection" resource APIs
  ######################################################
  /applications:
    get:
      tags:
        - Application (Collection)
      summary: |
        Retrieve/Search Applications
      description: |
        This operation can be used to retrieve list of applications owned by the given user, If no user
        is provided, the applications owned by the user associated with the provided access token will be returned.
      security:
        - OAuth2Security:
            - apk:admin_application_manage
      operationId: getApplicationsByUser

  ######################################################
  # The "Individual Application" resource APIs
  ######################################################
  /applications/{applicationId}:
    get:
      tags:
        - Applications
      summary: |
        Get the details of an Application
      description: |
        This operation can be used to get the details of an application by specifying its id.
      security:
        - OAuth2Security:
            - apk:admin_application_manage
      operationId: getApplicationById

    delete:
      tags:
        - Applications
      summary: |
        Delete an Application
      description: |
        This operation can be used to delete an application by specifying its id.
      security:
        - OAuth2Security:
            - apk:admin_application_manage
      operationId: removeApplication

  /applications/{applicationId}/change-owner:
    post:
      tags:
        - Application
      summary: Change Application Owner
      description: |
        This operation is used to change the owner of an Application.
        In order to change the owner of an application, we need to pass the new application owner as a query parameter
      security:
        - OAuth2Security:
            - apk:admin_application_manage
      operationId: changeApplicationOwner

  ######################################################
  # The "Environment" resource API
  ######################################################
  /environments:
    get:
      tags:
        - Environments
      summary: Get all registered Environments
      description: |
        Get all Registered Environments
      security:
        - OAuth2Security:
            - apk:admin
            - apk:environment_read
      operationId: getEnvironments

    post:
      tags:
        - Environments
      summary: Add an Environment
      description: |
        Add a new gateway environment
      security:
        - OAuth2Security:
            - apk:admin
            - apk:environment_manage
      operationId: addEnvironment

  ######################################################
  # The "Individual Environment" resource APIs
  ######################################################
  /environments/{environmentId}:
    put:
      tags:
        - Environments
      summary: Update an Environment
      description: |
        Update a gateway Environment by environment Id
      security:
        - OAuth2Security:
            - apk:admin
            - apk:environment_manage
      operationId: updateEnvironment

    delete:
      tags:
        - Environments
      summary: Delete an Environment
      description: |
        Delete a Environment by Environment Id
      security:
        - OAuth2Security:
            - apk:admin
            - apk:environment_manage
      operationId: removeEnvironment


  ######################################################
  # The Tenant Info resource API
  ######################################################
  /tenant-info/{username}:
    get:
      tags:
        - Tenants
      summary: |
        Get Tenant Id of User
      description: |
        This operation is to get tenant id of the provided user
      operationId: getTenantInfoByUsername
      security:
        - OAuth2Security:
            - apk:admin
            - apk:tenantInfo
  ######################################################
  # The Custom URL Info resource API
  ######################################################
  /custom-urls/{tenantDomain}:
    get:
      tags:
        - Tenants
      summary: |
        Get Custom URL Info of a Tenant Domain
      description: |
        This operation is to get custom-url information of the provided tenant-domain
      operationId: getCustomUrlInfoByTenantDomain
      security:
        - OAuth2Security:
            - apk:admin
            - apk:tenantInfo
  ######################################################
  # The "Category Collection" resource API
  ######################################################
  /api-categories:
    get:
      tags:
        - API Category (Collection)
      summary: Get all API Categories
      description: |
        Get all API categories
      security:
        - OAuth2Security:
            - apk:category_manage
      operationId: getAllCategories

    post:
      tags:
        - API Category (Individual)
      summary: Add API Category
      description: |
        Add a new API category
      security:
        - OAuth2Security:
            - apk:category_manage
      operationId: addCategory

  ######################################################
  # The "Individual Category" resource APIs
  ######################################################
  /api-categories/{apiCategoryId}:
    put:
      tags:
        - API Category (Individual)
      summary: Update an API Category
      description: |
        Update an API Category by category Id
      security:
        - OAuth2Security:
            - apk:category_manage
      operationId: updateCategory

    delete:
      tags:
        - API Category (Individual)
      summary: Delete an API Category
      description: |
        Delete an API Category by API Category Id
      security:
        - OAuth2Security:
            - apk:category_manage
      operationId: removeCategory

  ######################################################
  # The Admin settings List
  ######################################################
  /settings:
    get:
      tags:
        - Settings
      summary: Retrieve Admin Settings
      description: |
        Retrieve admin settings
      operationId: getAdminSettings

  ######################################################
  # The "Key Manager Collection" resource API
  ######################################################
  /key-managers:
    get:
      tags:
        - Key Manager (Collection)
      summary: Get all Key managers
      description: |
        Get all Key managers
      security:
        - OAuth2Security:
            - apk:keymanager_operations
      operationId: getAllKeyManagers

    post:
      tags:
        - Key Manager (Collection)
      summary: Add a new API Key Manager
      description: |
        Add a new API Key Manager
      security:
        - OAuth2Security:
            - apk:keymanager_operations
      operationId: addNewKeyManager

  ######################################################
  # The "Individual KeyManager" resource APIs
  ######################################################
  /key-managers/{keyManagerId}:
    get:
      tags:
        - Key Manager (Individual)
      summary: Get a Key Manager Configuration
      description: |
        Retrieve a single Key Manager Configuration. We should provide the Id of the KeyManager as a path parameter.
      security:
        - OAuth2Security:
            - apk:keymanager_operations
      operationId: getKeyManagerConfiguration

    put:
      tags:
        - Key Manager (Individual)
      summary: Update a Key Manager
      description: |
        Update a Key Manager by keyManager ID
      security:
        - OAuth2Security:
            - apk:keymanager_operations
      operationId: updateKeyManager

    delete:
      tags:
        - Key Manager (Individual)
      summary: Delete a Key Manager
      description: |
        Delete a Key Manager by keyManager id
      security:
        - OAuth2Security:
            - apk:keymanager_operations
      operationId: removeKeyManager

  /key-managers/discover:
    post:
      tags:
        - Key Manager (Collection)
      summary: Retrieve Well-known information from Key Manager Well-known Endpoint
      description: |
        Retrieve well-known information from key manager's well-known endpoint
      security:
        - OAuth2Security:
            - apk:keymanager_operations
      operationId: getWellKnownInfoKeyManager

######################################################
  # The "Organization" resource API
######################################################
  /organizations:
    get:
      tags:
        - Organization (Collection)
      summary: Get all Organization
      description: |
        Get all Organization
      security:
        - OAuth2Security:
            - apk:organization_manage
      operationId: getAllOrganization

    post:
      tags:
        - Organization (Individual)
      summary: Add Organization
      description: |
        Add a new Organization
      security:
        - OAuth2Security:
            - apk:organization_manage
      operationId: addOrganization
  /organizations/{organizationId}:
    get:
      tags:
        - Organization (Individual)
      summary: |
        Get the details of an Organization
      description: |
        This operation can be used to get the details of an Organization by specifying its id.
      security:
        - OAuth2Security:
            - apk:organization_manage
      operationId: getOrganizationById
    put:
      tags:
        - Organization (Individual)
      summary: Update an Organization
      description: |
        Update an Organization by organization Id
      security:
        - OAuth2Security:
            - apk:organization_manage
      operationId: updateOrganization
    delete:
      tags:
        - Organization (Individual)
      summary: Delete an Organization
      description: |
        Delete an Organization by API Organization Id
      security:
        - OAuth2Security:
            - apk:organization_manage
      operationId: removeOrganization
  /organization-info:
    get:
      tags:
        - Organization (Individual)
      summary: |
        Authenticate Organization info
      description: |
        This operation can be used to authenticate Organization by specifying its claimValue.
      security:
        - OAuth2Security:
            - apk:organization_manage
      operationId: getOrganizationByClaimValue

components:
  securitySchemes:
    OAuth2Security:
      type: oauth2
      flows:
        password:
          tokenUrl: https://localhost:9443/oauth2/token
          scopes:
            openid: Authorize access to user details
            apk:organization_manage: Manage all organization
            apk:admin: Manage all admin operations
            apk:tier_manage: Update and delete throttling policies
            apk:bl_manage: Update and delete deny policies
            apk:environment_manage: Manage gateway environments
            apk:category_manage: Manage API Categories
            apk:keymanager_operations: Manage Key Managers related
              operations
            apk:admin_application_manage: Manage All Applications
            