// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/api/ai_provider.proto

package org.wso2.apk.enforcer.discovery.api;

public final class AIProviderProto {
  private AIProviderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wso2_discovery_api_AIProvider_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wso2_discovery_api_AIProvider_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wso2_discovery_api_ValueDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wso2_discovery_api_ValueDetails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$wso2/discovery/api/ai_provider.proto\022\022" +
      "wso2.discovery.api\"\277\002\n\nAIProvider\022\024\n\014pro" +
      "viderName\030\001 \001(\t\022\032\n\022providerAPIVersion\030\002 " +
      "\001(\t\022\024\n\014organization\030\003 \001(\t\022/\n\005model\030\004 \001(\013" +
      "2 .wso2.discovery.api.ValueDetails\0226\n\014pr" +
      "omptTokens\030\005 \001(\0132 .wso2.discovery.api.Va" +
      "lueDetails\0229\n\017completionToken\030\006 \001(\0132 .ws" +
      "o2.discovery.api.ValueDetails\0224\n\ntotalTo" +
      "ken\030\007 \001(\0132 .wso2.discovery.api.ValueDeta" +
      "ils\022\017\n\007enabled\030\010 \001(\010\")\n\014ValueDetails\022\n\n\002" +
      "in\030\001 \001(\t\022\r\n\005value\030\002 \001(\tBw\n#org.wso2.apk." +
      "enforcer.discovery.apiB\017AIProviderProtoP" +
      "\001Z=github.com/envoyproxy/go-control-plan" +
      "e/wso2/discovery/api;apib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_wso2_discovery_api_AIProvider_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wso2_discovery_api_AIProvider_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wso2_discovery_api_AIProvider_descriptor,
        new java.lang.String[] { "ProviderName", "ProviderAPIVersion", "Organization", "Model", "PromptTokens", "CompletionToken", "TotalToken", "Enabled", });
    internal_static_wso2_discovery_api_ValueDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wso2_discovery_api_ValueDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wso2_discovery_api_ValueDetails_descriptor,
        new java.lang.String[] { "In", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
