// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/api/BackendJWTTokenInfo.proto

package org.wso2.apk.enforcer.discovery.api;

/**
 * <pre>
 * Endpoint config model
 * </pre>
 *
 * Protobuf type {@code wso2.discovery.api.BackendJWTTokenInfo}
 */
public final class BackendJWTTokenInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wso2.discovery.api.BackendJWTTokenInfo)
    BackendJWTTokenInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BackendJWTTokenInfo.newBuilder() to construct.
  private BackendJWTTokenInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BackendJWTTokenInfo() {
    encoding_ = "";
    header_ = "";
    signingAlgorithm_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BackendJWTTokenInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BackendJWTTokenInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            enabled_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            encoding_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            header_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            signingAlgorithm_ = s;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              customClaims_ = com.google.protobuf.MapField.newMapField(
                  CustomClaimsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim>
            customClaims__ = input.readMessage(
                CustomClaimsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            customClaims_.getMutableMap().put(
                customClaims__.getKey(), customClaims__.getValue());
            break;
          }
          case 48: {

            tokenTTL_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfoProto.internal_static_wso2_discovery_api_BackendJWTTokenInfo_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 5:
        return internalGetCustomClaims();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfoProto.internal_static_wso2_discovery_api_BackendJWTTokenInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo.class, org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo.Builder.class);
  }

  public static final int ENABLED_FIELD_NUMBER = 1;
  private boolean enabled_;
  /**
   * <code>bool enabled = 1;</code>
   * @return The enabled.
   */
  @java.lang.Override
  public boolean getEnabled() {
    return enabled_;
  }

  public static final int ENCODING_FIELD_NUMBER = 2;
  private volatile java.lang.Object encoding_;
  /**
   * <code>string encoding = 2;</code>
   * @return The encoding.
   */
  @java.lang.Override
  public java.lang.String getEncoding() {
    java.lang.Object ref = encoding_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      encoding_ = s;
      return s;
    }
  }
  /**
   * <code>string encoding = 2;</code>
   * @return The bytes for encoding.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEncodingBytes() {
    java.lang.Object ref = encoding_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      encoding_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEADER_FIELD_NUMBER = 3;
  private volatile java.lang.Object header_;
  /**
   * <code>string header = 3;</code>
   * @return The header.
   */
  @java.lang.Override
  public java.lang.String getHeader() {
    java.lang.Object ref = header_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      header_ = s;
      return s;
    }
  }
  /**
   * <code>string header = 3;</code>
   * @return The bytes for header.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHeaderBytes() {
    java.lang.Object ref = header_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      header_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIGNINGALGORITHM_FIELD_NUMBER = 4;
  private volatile java.lang.Object signingAlgorithm_;
  /**
   * <code>string signingAlgorithm = 4;</code>
   * @return The signingAlgorithm.
   */
  @java.lang.Override
  public java.lang.String getSigningAlgorithm() {
    java.lang.Object ref = signingAlgorithm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      signingAlgorithm_ = s;
      return s;
    }
  }
  /**
   * <code>string signingAlgorithm = 4;</code>
   * @return The bytes for signingAlgorithm.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSigningAlgorithmBytes() {
    java.lang.Object ref = signingAlgorithm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      signingAlgorithm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMCLAIMS_FIELD_NUMBER = 5;
  private static final class CustomClaimsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim>newDefaultInstance(
                org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfoProto.internal_static_wso2_discovery_api_BackendJWTTokenInfo_CustomClaimsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                org.wso2.apk.enforcer.discovery.api.Claim.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim> customClaims_;
  private com.google.protobuf.MapField<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim>
  internalGetCustomClaims() {
    if (customClaims_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          CustomClaimsDefaultEntryHolder.defaultEntry);
    }
    return customClaims_;
  }

  public int getCustomClaimsCount() {
    return internalGetCustomClaims().getMap().size();
  }
  /**
   * <code>map&lt;string, .wso2.discovery.api.Claim&gt; customClaims = 5;</code>
   */

  @java.lang.Override
  public boolean containsCustomClaims(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetCustomClaims().getMap().containsKey(key);
  }
  /**
   * Use {@link #getCustomClaimsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim> getCustomClaims() {
    return getCustomClaimsMap();
  }
  /**
   * <code>map&lt;string, .wso2.discovery.api.Claim&gt; customClaims = 5;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim> getCustomClaimsMap() {
    return internalGetCustomClaims().getMap();
  }
  /**
   * <code>map&lt;string, .wso2.discovery.api.Claim&gt; customClaims = 5;</code>
   */
  @java.lang.Override

  public org.wso2.apk.enforcer.discovery.api.Claim getCustomClaimsOrDefault(
      java.lang.String key,
      org.wso2.apk.enforcer.discovery.api.Claim defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim> map =
        internalGetCustomClaims().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .wso2.discovery.api.Claim&gt; customClaims = 5;</code>
   */
  @java.lang.Override

  public org.wso2.apk.enforcer.discovery.api.Claim getCustomClaimsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim> map =
        internalGetCustomClaims().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TOKENTTL_FIELD_NUMBER = 6;
  private int tokenTTL_;
  /**
   * <code>int32 tokenTTL = 6;</code>
   * @return The tokenTTL.
   */
  @java.lang.Override
  public int getTokenTTL() {
    return tokenTTL_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (enabled_ != false) {
      output.writeBool(1, enabled_);
    }
    if (!getEncodingBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, encoding_);
    }
    if (!getHeaderBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, header_);
    }
    if (!getSigningAlgorithmBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, signingAlgorithm_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetCustomClaims(),
        CustomClaimsDefaultEntryHolder.defaultEntry,
        5);
    if (tokenTTL_ != 0) {
      output.writeInt32(6, tokenTTL_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (enabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, enabled_);
    }
    if (!getEncodingBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, encoding_);
    }
    if (!getHeaderBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, header_);
    }
    if (!getSigningAlgorithmBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, signingAlgorithm_);
    }
    for (java.util.Map.Entry<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim> entry
         : internalGetCustomClaims().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim>
      customClaims__ = CustomClaimsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, customClaims__);
    }
    if (tokenTTL_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, tokenTTL_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo)) {
      return super.equals(obj);
    }
    org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo other = (org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo) obj;

    if (getEnabled()
        != other.getEnabled()) return false;
    if (!getEncoding()
        .equals(other.getEncoding())) return false;
    if (!getHeader()
        .equals(other.getHeader())) return false;
    if (!getSigningAlgorithm()
        .equals(other.getSigningAlgorithm())) return false;
    if (!internalGetCustomClaims().equals(
        other.internalGetCustomClaims())) return false;
    if (getTokenTTL()
        != other.getTokenTTL()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEnabled());
    hash = (37 * hash) + ENCODING_FIELD_NUMBER;
    hash = (53 * hash) + getEncoding().hashCode();
    hash = (37 * hash) + HEADER_FIELD_NUMBER;
    hash = (53 * hash) + getHeader().hashCode();
    hash = (37 * hash) + SIGNINGALGORITHM_FIELD_NUMBER;
    hash = (53 * hash) + getSigningAlgorithm().hashCode();
    if (!internalGetCustomClaims().getMap().isEmpty()) {
      hash = (37 * hash) + CUSTOMCLAIMS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetCustomClaims().hashCode();
    }
    hash = (37 * hash) + TOKENTTL_FIELD_NUMBER;
    hash = (53 * hash) + getTokenTTL();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Endpoint config model
   * </pre>
   *
   * Protobuf type {@code wso2.discovery.api.BackendJWTTokenInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wso2.discovery.api.BackendJWTTokenInfo)
      org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfoProto.internal_static_wso2_discovery_api_BackendJWTTokenInfo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetCustomClaims();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetMutableCustomClaims();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfoProto.internal_static_wso2_discovery_api_BackendJWTTokenInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo.class, org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo.Builder.class);
    }

    // Construct using org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      enabled_ = false;

      encoding_ = "";

      header_ = "";

      signingAlgorithm_ = "";

      internalGetMutableCustomClaims().clear();
      tokenTTL_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfoProto.internal_static_wso2_discovery_api_BackendJWTTokenInfo_descriptor;
    }

    @java.lang.Override
    public org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo getDefaultInstanceForType() {
      return org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo.getDefaultInstance();
    }

    @java.lang.Override
    public org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo build() {
      org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo buildPartial() {
      org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo result = new org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo(this);
      int from_bitField0_ = bitField0_;
      result.enabled_ = enabled_;
      result.encoding_ = encoding_;
      result.header_ = header_;
      result.signingAlgorithm_ = signingAlgorithm_;
      result.customClaims_ = internalGetCustomClaims();
      result.customClaims_.makeImmutable();
      result.tokenTTL_ = tokenTTL_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo) {
        return mergeFrom((org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo other) {
      if (other == org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo.getDefaultInstance()) return this;
      if (other.getEnabled() != false) {
        setEnabled(other.getEnabled());
      }
      if (!other.getEncoding().isEmpty()) {
        encoding_ = other.encoding_;
        onChanged();
      }
      if (!other.getHeader().isEmpty()) {
        header_ = other.header_;
        onChanged();
      }
      if (!other.getSigningAlgorithm().isEmpty()) {
        signingAlgorithm_ = other.signingAlgorithm_;
        onChanged();
      }
      internalGetMutableCustomClaims().mergeFrom(
          other.internalGetCustomClaims());
      if (other.getTokenTTL() != 0) {
        setTokenTTL(other.getTokenTTL());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean enabled_ ;
    /**
     * <code>bool enabled = 1;</code>
     * @return The enabled.
     */
    @java.lang.Override
    public boolean getEnabled() {
      return enabled_;
    }
    /**
     * <code>bool enabled = 1;</code>
     * @param value The enabled to set.
     * @return This builder for chaining.
     */
    public Builder setEnabled(boolean value) {
      
      enabled_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool enabled = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnabled() {
      
      enabled_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object encoding_ = "";
    /**
     * <code>string encoding = 2;</code>
     * @return The encoding.
     */
    public java.lang.String getEncoding() {
      java.lang.Object ref = encoding_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        encoding_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string encoding = 2;</code>
     * @return The bytes for encoding.
     */
    public com.google.protobuf.ByteString
        getEncodingBytes() {
      java.lang.Object ref = encoding_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        encoding_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string encoding = 2;</code>
     * @param value The encoding to set.
     * @return This builder for chaining.
     */
    public Builder setEncoding(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      encoding_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string encoding = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncoding() {
      
      encoding_ = getDefaultInstance().getEncoding();
      onChanged();
      return this;
    }
    /**
     * <code>string encoding = 2;</code>
     * @param value The bytes for encoding to set.
     * @return This builder for chaining.
     */
    public Builder setEncodingBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      encoding_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object header_ = "";
    /**
     * <code>string header = 3;</code>
     * @return The header.
     */
    public java.lang.String getHeader() {
      java.lang.Object ref = header_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        header_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string header = 3;</code>
     * @return The bytes for header.
     */
    public com.google.protobuf.ByteString
        getHeaderBytes() {
      java.lang.Object ref = header_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        header_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string header = 3;</code>
     * @param value The header to set.
     * @return This builder for chaining.
     */
    public Builder setHeader(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      header_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string header = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeader() {
      
      header_ = getDefaultInstance().getHeader();
      onChanged();
      return this;
    }
    /**
     * <code>string header = 3;</code>
     * @param value The bytes for header to set.
     * @return This builder for chaining.
     */
    public Builder setHeaderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      header_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object signingAlgorithm_ = "";
    /**
     * <code>string signingAlgorithm = 4;</code>
     * @return The signingAlgorithm.
     */
    public java.lang.String getSigningAlgorithm() {
      java.lang.Object ref = signingAlgorithm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        signingAlgorithm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string signingAlgorithm = 4;</code>
     * @return The bytes for signingAlgorithm.
     */
    public com.google.protobuf.ByteString
        getSigningAlgorithmBytes() {
      java.lang.Object ref = signingAlgorithm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signingAlgorithm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string signingAlgorithm = 4;</code>
     * @param value The signingAlgorithm to set.
     * @return This builder for chaining.
     */
    public Builder setSigningAlgorithm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      signingAlgorithm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string signingAlgorithm = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSigningAlgorithm() {
      
      signingAlgorithm_ = getDefaultInstance().getSigningAlgorithm();
      onChanged();
      return this;
    }
    /**
     * <code>string signingAlgorithm = 4;</code>
     * @param value The bytes for signingAlgorithm to set.
     * @return This builder for chaining.
     */
    public Builder setSigningAlgorithmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      signingAlgorithm_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim> customClaims_;
    private com.google.protobuf.MapField<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim>
    internalGetCustomClaims() {
      if (customClaims_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CustomClaimsDefaultEntryHolder.defaultEntry);
      }
      return customClaims_;
    }
    private com.google.protobuf.MapField<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim>
    internalGetMutableCustomClaims() {
      onChanged();;
      if (customClaims_ == null) {
        customClaims_ = com.google.protobuf.MapField.newMapField(
            CustomClaimsDefaultEntryHolder.defaultEntry);
      }
      if (!customClaims_.isMutable()) {
        customClaims_ = customClaims_.copy();
      }
      return customClaims_;
    }

    public int getCustomClaimsCount() {
      return internalGetCustomClaims().getMap().size();
    }
    /**
     * <code>map&lt;string, .wso2.discovery.api.Claim&gt; customClaims = 5;</code>
     */

    @java.lang.Override
    public boolean containsCustomClaims(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetCustomClaims().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCustomClaimsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim> getCustomClaims() {
      return getCustomClaimsMap();
    }
    /**
     * <code>map&lt;string, .wso2.discovery.api.Claim&gt; customClaims = 5;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim> getCustomClaimsMap() {
      return internalGetCustomClaims().getMap();
    }
    /**
     * <code>map&lt;string, .wso2.discovery.api.Claim&gt; customClaims = 5;</code>
     */
    @java.lang.Override

    public org.wso2.apk.enforcer.discovery.api.Claim getCustomClaimsOrDefault(
        java.lang.String key,
        org.wso2.apk.enforcer.discovery.api.Claim defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim> map =
          internalGetCustomClaims().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .wso2.discovery.api.Claim&gt; customClaims = 5;</code>
     */
    @java.lang.Override

    public org.wso2.apk.enforcer.discovery.api.Claim getCustomClaimsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim> map =
          internalGetCustomClaims().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearCustomClaims() {
      internalGetMutableCustomClaims().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .wso2.discovery.api.Claim&gt; customClaims = 5;</code>
     */

    public Builder removeCustomClaims(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableCustomClaims().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim>
    getMutableCustomClaims() {
      return internalGetMutableCustomClaims().getMutableMap();
    }
    /**
     * <code>map&lt;string, .wso2.discovery.api.Claim&gt; customClaims = 5;</code>
     */
    public Builder putCustomClaims(
        java.lang.String key,
        org.wso2.apk.enforcer.discovery.api.Claim value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableCustomClaims().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .wso2.discovery.api.Claim&gt; customClaims = 5;</code>
     */

    public Builder putAllCustomClaims(
        java.util.Map<java.lang.String, org.wso2.apk.enforcer.discovery.api.Claim> values) {
      internalGetMutableCustomClaims().getMutableMap()
          .putAll(values);
      return this;
    }

    private int tokenTTL_ ;
    /**
     * <code>int32 tokenTTL = 6;</code>
     * @return The tokenTTL.
     */
    @java.lang.Override
    public int getTokenTTL() {
      return tokenTTL_;
    }
    /**
     * <code>int32 tokenTTL = 6;</code>
     * @param value The tokenTTL to set.
     * @return This builder for chaining.
     */
    public Builder setTokenTTL(int value) {
      
      tokenTTL_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 tokenTTL = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTokenTTL() {
      
      tokenTTL_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wso2.discovery.api.BackendJWTTokenInfo)
  }

  // @@protoc_insertion_point(class_scope:wso2.discovery.api.BackendJWTTokenInfo)
  private static final org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo();
  }

  public static org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BackendJWTTokenInfo>
      PARSER = new com.google.protobuf.AbstractParser<BackendJWTTokenInfo>() {
    @java.lang.Override
    public BackendJWTTokenInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BackendJWTTokenInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BackendJWTTokenInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BackendJWTTokenInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.wso2.apk.enforcer.discovery.api.BackendJWTTokenInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

