// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/api/Certificate.proto

package org.wso2.apk.enforcer.discovery.api;

public interface CertificateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wso2.discovery.api.Certificate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alias = 1;</code>
   * @return The alias.
   */
  java.lang.String getAlias();
  /**
   * <code>string alias = 1;</code>
   * @return The bytes for alias.
   */
  com.google.protobuf.ByteString
      getAliasBytes();

  /**
   * <code>bytes content = 2;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();
}
