// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/api/api_authentication.proto

package org.wso2.apk.enforcer.discovery.api;

public interface Oauth2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:wso2.discovery.api.Oauth2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * name of the header containing the JWT
   * </pre>
   *
   * <code>string header = 1;</code>
   * @return The header.
   */
  java.lang.String getHeader();
  /**
   * <pre>
   * name of the header containing the JWT
   * </pre>
   *
   * <code>string header = 1;</code>
   * @return The bytes for header.
   */
  com.google.protobuf.ByteString
      getHeaderBytes();

  /**
   * <pre>
   * send the token to upstream
   * </pre>
   *
   * <code>bool sendTokenToUpstream = 2;</code>
   * @return The sendTokenToUpstream.
   */
  boolean getSendTokenToUpstream();
}
