// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wso2/discovery/api/Resource.proto

package org.wso2.apk.enforcer.discovery.api;

public interface ResourceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wso2.discovery.api.Resource)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string path = 2;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 2;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <code>repeated .wso2.discovery.api.Operation methods = 3;</code>
   */
  java.util.List<org.wso2.apk.enforcer.discovery.api.Operation> 
      getMethodsList();
  /**
   * <code>repeated .wso2.discovery.api.Operation methods = 3;</code>
   */
  org.wso2.apk.enforcer.discovery.api.Operation getMethods(int index);
  /**
   * <code>repeated .wso2.discovery.api.Operation methods = 3;</code>
   */
  int getMethodsCount();
  /**
   * <code>repeated .wso2.discovery.api.Operation methods = 3;</code>
   */
  java.util.List<? extends org.wso2.apk.enforcer.discovery.api.OperationOrBuilder> 
      getMethodsOrBuilderList();
  /**
   * <code>repeated .wso2.discovery.api.Operation methods = 3;</code>
   */
  org.wso2.apk.enforcer.discovery.api.OperationOrBuilder getMethodsOrBuilder(
      int index);

  /**
   * <code>.wso2.discovery.api.EndpointCluster endpoints = 4;</code>
   * @return Whether the endpoints field is set.
   */
  boolean hasEndpoints();
  /**
   * <code>.wso2.discovery.api.EndpointCluster endpoints = 4;</code>
   * @return The endpoints.
   */
  org.wso2.apk.enforcer.discovery.api.EndpointCluster getEndpoints();
  /**
   * <code>.wso2.discovery.api.EndpointCluster endpoints = 4;</code>
   */
  org.wso2.apk.enforcer.discovery.api.EndpointClusterOrBuilder getEndpointsOrBuilder();

  /**
   * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 5;</code>
   */
  java.util.List<org.wso2.apk.enforcer.discovery.api.SecurityInfo> 
      getEndpointSecurityList();
  /**
   * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 5;</code>
   */
  org.wso2.apk.enforcer.discovery.api.SecurityInfo getEndpointSecurity(int index);
  /**
   * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 5;</code>
   */
  int getEndpointSecurityCount();
  /**
   * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 5;</code>
   */
  java.util.List<? extends org.wso2.apk.enforcer.discovery.api.SecurityInfoOrBuilder> 
      getEndpointSecurityOrBuilderList();
  /**
   * <code>repeated .wso2.discovery.api.SecurityInfo endpointSecurity = 5;</code>
   */
  org.wso2.apk.enforcer.discovery.api.SecurityInfoOrBuilder getEndpointSecurityOrBuilder(
      int index);
}
