# Copyright (c) 2025 WSO2 LLC. (http://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
{{- if and .Values.wso2.kgw.dp.enabled .Values.wso2.kgw.dp.configdeployer.enabled }}
apiVersion: "dp.wso2.com/v2alpha1"
kind: "RouteMetadata"
metadata:
  name: {{ template "kubernetes-gateway-helm.resource.prefix" . }}-config-api-routemetadata
  namespace: {{ .Release.Namespace }}
  labels:
    api-name: "{{ template "kubernetes-gateway-helm.resource.prefix" . }}-config-api"
    api-version: "2.0.0"
    managed-by: "kgw"
spec:
  api:
    name: {{ template "kubernetes-gateway-helm.resource.prefix" . }}-config-api
    version: 2.0.0
    context: /api/configurator
{{- end -}}
