apiVersion: dp.wso2.com/v1alpha1
kind: APIPolicy
metadata:
  name: backend-jwt-token-policy
spec:
  override:
    backendJwtToken:
      enabled: true
      encoding: "base64"
      signingAlgorithm: "SHA256withRSA"
      header: "X-JWT-Assertion"
      tokenTTL: 3600
      customClaims:
        - claim: "admin"
          value: "http://wso2.org/claims/enduser"
    cORSPolicy:
      enabled: true
      accessControlAllowCredentials: false
      accessControlAllowOrigins:
        - "*"
      accessControlAllowHeaders:
        - authorization
      accessControlAllowMethods:
        - GET
        - POST
      accessControlExposeHeaders:
        - "*"
  targetRef:
    group: gateway.networking.k8s.io
    kind: API
    name: http-bin-api
