{{- if and .Values.wso2.kgw.dp.enabled .Values.wso2.kgw.dp.configdeployer.enabled }}
apiVersion: dp.wso2.com/v1alpha1
kind: BackendJWT
metadata:
  name: "{{ template "kubernetes-gateway-helm.resource.prefix" . }}-config-api-backendjwt"
  namespace: {{ .Release.Namespace }}
  labels:
    managed-by: "kgw"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
    header: "X-JWT-Assertion"
    encoding: "Base64"
    signingAlgorithm: "SHA256withRSA"
    tokenTTL: 3600
{{- end}}