# The logging configuration file for APK Agent
######### root Level ########
logfile = "logs/adapter.log"
logLevel = "INFO"

[rotation]
MaxSize = 10    #megabytes
MaxBackups = 3
MaxAge =  2   #days
Compress = true

######### package Level ############
# LogLevels = "DEBG", "FATL", "ERRO", "WARN", "INFO", "PANC"

# [[pkg]]
# name = "github.com/wso2/apk/management-server/xds"
# logLevel = "INFO"
