apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.wso2.apk.dp.gateway.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/issuer: selfsigned-issuer
spec:
  gatewayClassName: {{ .Values.wso2.apk.dp.gateway.name }}
  listeners:
    - name: examplelistener
      hostname: "*.example.com"
      port: {{ .Values.wso2.apk.dp.gateway.listener.port }}
      protocol: {{ .Values.wso2.apk.dp.gateway.listener.protocol }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: {{ template "apk-helm.resource.prefix" . }}-example-listener-cert
            namespace: {{ .Release.Namespace }}
    - name: apilistener
      hostname: "api.am.wso2.com"
      port: {{ .Values.wso2.apk.dp.gateway.listener.port }}
      protocol: {{ .Values.wso2.apk.dp.gateway.listener.protocol }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: {{ template "apk-helm.resource.prefix" . }}-system-api-listener-cert
            namespace: {{ .Release.Namespace }}
    - name: idplistener
      hostname: "idp.am.wso2.com"
      port: {{ .Values.wso2.apk.dp.gateway.listener.port }}
      protocol: {{ .Values.wso2.apk.dp.gateway.listener.protocol }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: {{ template "apk-helm.resource.prefix" . }}-idp-listener-cert
            namespace: {{ .Release.Namespace }}
    - name: gatewaylistener
      hostname: "{{ .Values.wso2.apk.dp.gateway.listener.hostname }}"
      port: {{ .Values.wso2.apk.dp.gateway.listener.port }}
      protocol: {{ .Values.wso2.apk.dp.gateway.listener.protocol }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: {{ template "apk-helm.resource.prefix" . }}-gw-listener-cert
            namespace: {{ .Release.Namespace }}
    - name: systemlistener
      hostname: "localhost"
      port: {{ .Values.wso2.apk.dp.gateway.listener.port }}
      protocol: {{ .Values.wso2.apk.dp.gateway.listener.protocol }}
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: {{ template "apk-helm.resource.prefix" . }}-localhost-listener-cert
            namespace: {{ .Release.Namespace }}