{{- if .Values.wso2.apk.dp.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.wso2.apk.dp.gateway.name | default "wso2-apk-default" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/issuer: {{ template "apk-helm.resource.prefix" . }}-selfsigned-issuer
spec:
  {{- if .Values.wso2.apk.dp.gatewayClass }}
  gatewayClassName: {{ .Values.wso2.apk.dp.gatewayClass.name | default "wso2-apk-default" }}
  {{- else }}
  gatewayClassName: "wso2-apk-default"
  {{- end }}
  listeners:
    {{ if and .Values.wso2.apk.dp.gateway.httpListener .Values.wso2.apk.dp.gateway.httpListener.enabled }}
    - name: httplistener
      hostname: "{{ .Values.wso2.apk.dp.gateway.httpListener.hostname | default "api.am.wso2.com"}}"
      port: {{ .Values.wso2.apk.dp.gateway.httpListener.port | default 9080}}
      protocol: HTTP
    {{ end }}
    {{- if .Values.wso2.apk.dp.enabled }}
    - name: httpslistener
      hostname: "*.{{ .Values.wso2.apk.dp.gateway.listener.hostname }}"
      port: 9095
      protocol: "HTTPS"
      allowedRoutes:
        namespaces: 
          from: "All"
      tls:  
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: {{ .Values.wso2.apk.dp.gateway.listener.secretName | default (printf "%s-gw-listener-cert" (include "apk-helm.resource.prefix" .)) }}
            namespace: {{ .Release.Namespace }}
    {{ end }}
    - name: apilistener
      hostname: "{{ .Values.wso2.apk.listener.hostname | default "api.am.wso2.com"}}"
      port: 9095
      protocol: "HTTPS"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: {{ .Values.wso2.apk.listener.secretName | default (printf "%s-system-api-listener-cert" (include "apk-helm.resource.prefix" .))}}
            namespace: {{ .Release.Namespace }}
    {{end}}
    {{ if and .Values.idp.enabled}}
    - name: idplistener
      hostname: "{{ .Values.idp.listener.hostname | default "idp.am.wso2.com"}}"
      port: 9095
      protocol: "HTTPS"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: {{ .Values.idp.listener.secretName | default (printf "%s-idp-listener-cert" (include "apk-helm.resource.prefix" .))}}
            namespace: {{ .Release.Namespace }}
    {{ end }}
    {{ if .Values.wso2.apk.dp.enabled }}
    - name: systemlistener
      hostname: "localhost"
      port: 9095
      protocol: "HTTPS"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ""
            name: {{ template "apk-helm.resource.prefix" . }}-localhost-listener-cert
            namespace: {{ .Release.Namespace }}
{{- end}}