// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: student.proto
// Protobuf Java Version: 4.28.0

package org.wso2.apk.integration.utils.clients.student_service;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apk.v1.student_service.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 3;</code>
   * 
   * @return The id.
   */
  int getId();
}
