// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: student.proto
// Protobuf Java Version: 4.28.0

package org.wso2.apk.integration.utils.clients.student_service;

public interface StudentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.apk.v1.student_service.StudentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * 
   * @return The name.
   */
  java.lang.String getName();

  /**
   * <code>string name = 1;</code>
   * 
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * 
   * @return The age.
   */
  int getAge();
}
