# [ballerina.log]
# level = "DEBUG"
# [ballerina.http]
# traceLogConsole = true
[wso2.config_deployer_service.k8sConfiguration]
host = "192.168.49.2:8443"
serviceAccountPath = "/media/tharindud/dev/satoken/runtime"
[wso2.config_deployer_service.keyStores.tls]
keyFilePath = "/media/tharindud/dev/satoken/runtime/runtime.key"
certFilePath = "/media/tharindud/dev/satoken/runtime/runtime.pem"
[wso2.config_deployer_service.gatewayConfiguration]
name = "default"
listenerName = "httpslistener"