openapi: 3.0.1
info:
  title: OAuth API
  description: OAuth API
  contact:
    name: WSO2
    url: http://wso2.com/products/api-manager/
    email: architecture@wso2.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths:
  /login:
    post:
      tags:
      - OAuth Token
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - username
              - password
              properties:
                username:
                  type: string
                  description: username
                password:
                  type: string
                  description: password
                organization:
                  type: string
                  description: organization
                sessionKey:
                  type: string
                  description: sessionKey
        required: true
      responses:
        302:
          description: Response from authorization endpoint
          headers:
            Location:
              schema:
                type: string
          content: {}
        401:
          description: |
            Unauthorized.
            Error response from token endpoint due to client authentication failure.
          headers:
            Content-Type:
              description: |
                The content type of the body.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginErrorResponse'
components:
  schemas:
    LoginErrorResponse:
      title: Error response sent for Login Error
      required:
      - error
      type: object
      properties:
        error:
          type: string
          description: Error code classifying the type of preProcessingError.
        error_description:
          type: string
