{{- if .Values.wso2.kgw.dp.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kubernetes-gateway-helm.resource.prefix" . }}-common-log-conf
  namespace: {{ .Release.Namespace }}
data:
  config.toml: | 
    [commoncontroller]
      {{- if and .Values.wso2.kgw.dp.environment .Values.wso2.kgw.dp.environment.name }}
      environment = "{{ .Values.wso2.kgw.dp.environment.name }}"
      {{- end }}
    {{if and .Values.wso2.kgw.metrics .Values.wso2.kgw.metrics.enabled}}
    [commoncontroller.metrics]
      enabled = {{.Values.wso2.kgw.metrics.enabled}}
      type = "{{.Values.wso2.kgw.metrics.type| default "prometheus" }}"
      port = 18006
    {{ end}}  
    [commoncontroller.server]
      label = "ratelimiter"
    {{ if and .Values.wso2.kgw.dp.commonController.deployment.configs .Values.wso2.kgw.dp.commonController.deployment.configs.apiNamespaces }}
    [commoncontroller.operator]
      namespaces = [{{ include "commaJoinedQuotedList" .Values.wso2.kgw.dp.commonController.deployment.configs.apiNamespaces}}]
    {{ end}}  
    [commoncontroller.keystore]
      certPath = "/home/wso2/security/keystore/commoncontroller.crt"
      keyPath = "/home/wso2/security/keystore/commoncontroller.key"

    [commoncontroller.truststore]
      location = "/home/wso2/security/truststore"
    
    {{- if .Values.wso2.kgw.cp }}
    [commoncontroller.controlplane]
       enabled = {{ .Values.wso2.kgw.cp.enabledSubscription | default false }}
       host = "{{ .Values.wso2.kgw.cp.host | default "apim-kgw-agent-service.kgw.svc.cluster.local" }}"
       enableAPIPropagation = {{ .Values.wso2.kgw.cp.enableApiPropagation | default false }}
       eventPort = {{ .Values.wso2.kgw.cp.port | default 18000 }}
       restPort = {{ .Values.wso2.kgw.cp.restPort | default 18001 }}
       skipSSLVerification = {{ .Values.wso2.kgw.cp.skipSSLVerification | default false }}
    {{- if and .Values.wso2.kgw.cp .Values.wso2.kgw.cp.persistence }}
    [commoncontroller.controlplane.persistence] 
      type = "{{ .Values.wso2.kgw.cp.persistence.type | default "K8s" }}"
    {{- end }}
    {{- end }}


    {{- if .Values.wso2.kgw.dp.commonController.deployment.database }}
    [commoncontroller.database]
      enabled = {{ .Values.wso2.kgw.dp.commonController.deployment.database.enabled | default false }}
      name = "{{ .Values.wso2.kgw.dp.commonController.deployment.database.name | default "DATAPLANE" }}"
      host = "{{ .Values.wso2.kgw.dp.commonController.deployment.database.host | default "wso2kgw-db-service.kgw" }}"
      port = {{ .Values.wso2.kgw.dp.commonController.deployment.database.port | default 5432 }}
      username = "{{ .Values.wso2.kgw.dp.commonController.deployment.database.username | default "wso2carbon" }}"
      password = "{{ .Values.wso2.kgw.dp.commonController.deployment.database.password | default "wso2carbon" }}"

      {{- if .Values.wso2.kgw.dp.commonController.deployment.database.poolOptions }}
      [commoncontroller.database.poolOptions]
        poolMaxConns = {{ .Values.wso2.kgw.dp.commonController.deployment.database.poolOptions.poolMaxConns | default 4 }}
        poolMinConns = {{ .Values.wso2.kgw.dp.commonController.deployment.database.poolOptions.poolMinConns | default 0 }}
        poolMaxConnLifetime = "{{ .Values.wso2.kgw.dp.commonController.deployment.database.poolOptions.poolMaxConnLifetime | default "1h" }}"
        poolMaxConnIdleTime = "{{ .Values.wso2.kgw.dp.commonController.deployment.database.poolOptions.poolMaxConnIdleTime | default "1h" }}"
        poolHealthCheckPeriod = "{{ .Values.wso2.kgw.dp.commonController.deployment.database.poolOptions.poolHealthCheckPeriod | default "1m" }}"
        poolMaxConnLifetimeJitter = "{{ .Values.wso2.kgw.dp.commonController.deployment.database.poolOptions.poolMaxConnLifetimeJitter | default "1s" }}"
      {{- end }}

    {{- end }}

    [commoncontroller.redis]
    {{- if .Values.wso2.kgw.dp.commonController.deployment.redis }}
      host = "{{ .Values.wso2.kgw.dp.commonController.deployment.redis.host | default "redis-master" }}"
      port = "{{ .Values.wso2.kgw.dp.commonController.deployment.redis.port | default "6379" }}"
      username = "{{ .Values.wso2.kgw.dp.commonController.deployment.redis.username | default "" }}"
      password = "{{ .Values.wso2.kgw.dp.commonController.deployment.redis.password | default "" }}"
      userCertPath = "{{ .Values.wso2.kgw.dp.commonController.deployment.redis.userCertPath | default "/home/wso2/security/keystore/commoncontroller.crt" }}"
      userKeyPath = "{{ .Values.wso2.kgw.dp.commonController.deployment.redis.userKeyPath | default "/home/wso2/security/keystore/commoncontroller.key" }}"
      cACertPath = "{{ .Values.wso2.kgw.dp.commonController.deployment.redis.redisCaCertPath | default "/home/wso2/security/keystore/commoncontroller.crt" }}"
      tLSEnabled = {{ .Values.wso2.kgw.dp.commonController.deployment.redis.tlsEnabled | default false }}
      revokedTokenChannel = "{{ .Values.wso2.kgw.dp.commonController.deployment.redis.channelName | default "wso2-kgw-revoked-tokens-channel" }}"
    {{- else }}
      host = "redis-master"
      port = "6379"
      username = "default"
      password = ""
      userCertPath = "/home/wso2/security/keystore/commoncontroller.crt"
      userKeyPath = "/home/wso2/security/keystore/commoncontroller.key"
      cACertPath = "/home/wso2/security/keystore/commoncontroller.crt"
      tlsEnabled = false
      revokedTokenChannel = "wso2-kgw-revoked-tokens-channel"
    {{- end }}
    [commoncontroller.sts]
      authKeyPath = "/home/wso2/security/sts/auth_key.txt"
      authKeyHeader = "stsAuthKey"
    
    [commoncontroller.webServer]
      port = 9543

  log_config.toml: |
    # The logging configuration for Adapter

    ## Common Controller root Level configurations

    {{- if .Values.wso2.kgw.dp.commonController.logging }}
    logLevel = "{{ .Values.wso2.kgw.dp.commonController.logging.level | default "INFO" }}" # LogLevels can be "DEBG", "FATL", "ERRO", "WARN", "INFO", "PANC"
    LogFormat = "{{ .Values.wso2.kgw.dp.commonController.logging.logFormat | default "TEXT" }}" # Values can be "JSON", "TEXT"
    {{- else }}
    logLevel = "INFO" # LogLevels can be "DEBG", "FATL", "ERRO", "WARN", "INFO", "PANC"
    LogFormat = "TEXT" # Values can be "JSON", "TEXT"
    {{- end }}

    [rotation]
    MaxSize = 10    # In MegaBytes (MB)
    MaxBackups = 3
    MaxAge =  2   # In days
    Compress = true


{{- end -}}
