# Copyright (c) 2022, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

{{- if .Values.wso2.apk.dp.enabled }}
{{- if and .Values.wso2.apk.dp.adapter .Values.wso2.apk.dp.adapter.deployment .Values.wso2.apk.dp.adapter.deployment.configs (not .Values.wso2.apk.dp.adapter.deployment.configs.enableGatewayClassController) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apk-helm.resource.prefix" . }}-gateway-service
  namespace : {{ .Release.Namespace }}
{{if and .Values.wso2.apk.dp.gatewayRuntime.service .Values.wso2.apk.dp.gatewayRuntime.service.annotations }}
  annotations:
{{ toYaml .Values.wso2.apk.dp.gatewayRuntime.service.annotations | indent 4 }}
{{ end }}
spec:
  type: {{ .Values.wso2.apk.dp.gateway.service.type | default "LoadBalancer" }}
  # label keys and values that must match in order to receive traffic for this service
  selector:
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" "gateway" ) | indent 4}}
  ports:
{{ if and .Values.wso2.apk.dp.gateway.httpListener .Values.wso2.apk.dp.gateway.httpListener.enabled }}
  - name: "http-endpoint"
    protocol: TCP
    port: {{ .Values.wso2.apk.dp.gateway.httpListener.port | default 9080 }}
{{ end }}
  - name: "https-endpoint"
    protocol: TCP
    port: 9095
{{- end -}}
{{- end -}}