{{ if or .Values.wso2.apk.dp.enabled .Values.wso2.apk.cp.enabled }}
kind: JWTIssuer
apiVersion: dp.wso2.com/v1alpha1
metadata:
  name: {{ template "apk-helm.resource.prefix" . }}-idp-jwt-issuer
  namespace: {{ .Release.Namespace }}
spec:
  name: "Domain-service-idp"
  consumerKeyClaim: {{ .Values.wso2.apk.idp.consumerKeyClaim | default "azp" }}
  scopesClaim: {{ .Values.wso2.apk.idp.scopeClaim | default "scope" }}
  issuer: "{{ .Values.wso2.apk.idp.issuer }}"
  organization: "carbon.super"
  signatureValidation:
  {{if and .Values.wso2.apk.idp.signing .Values.wso2.apk.idp.signing.configMapName .Values.wso2.apk.idp.signing.secretName }}
    certificate:
   {{if .Values.wso2.apk.idp.signing.secretName }}
      secretRef:
        name: "{{.Values.wso2.apk.idp.signing.secretName}}"
        key: "{{.Values.wso2.apk.idp.signing.fileName}}"
    {{else if .Values.wso2.apk.idp.signing.configMapName }}
      configMapRef:
        name: "{{.Values.wso2.apk.idp.signing.configMapName}}"
        key: "{{.Values.wso2.apk.idp.signing.fileName}}"
    {{end}}
    {{ else if and .Values.wso2.apk.idp.signing .Values.wso2.apk.idp.signing.jwksEndpoint }}
    jwks:
      url: "{{ .Values.wso2.apk.idp.signing.jwksEndpoint }}"
    {{if and .Values.wso2.apk.idp.tls.configMapName .Values.wso2.apk.idp.tls.secretName }}
      tls:
        {{if .Values.wso2.apk.idp.tls.secretName }}
        secretRef:
            name: "{{.Values.wso2.apk.idp.tls.secretName}}"
            key: "{{.Values.wso2.apk.idp.tls.fileName}}"
        {{else if .Values.wso2.apk.idp.tls.configMapName }}
        configMapRef:
            name: "{{.Values.wso2.apk.idp.tls.configMapName}}"
            key: "{{.Values.wso2.apk.idp.tls.fileName}}"
        {{end}}
    {{end}}
    {{else}}
    certificate:
      secretRef:
        name: "{{ template "apk-helm.resource.prefix" . }}-enforcer-truststore-secret"
        key: "wso2carbon.pem"
    {{ end }}
  targetRef:
    kind: Gateway
    name: default
    group: gateway.networking.k8s.io
{{- end -}}