apiVersion: dp.wso2.com/v1alpha2
kind: API
metadata:
  name: test-api-with-different-listener
  namespace: apk
spec:
  apiName: API with Different Listener
  apiType: REST
  apiVersion: 1.0.0
  basePath: /test-api-with-different-listener/v1.0.0
  #definitionFileRef: definition-file
  production:
    - routeRefs:
      - backend
  organization: wso2-org
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: apk
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: apk
  labels:
    app: backend
    service: backend
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: apk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      serviceAccountName: backend
      containers:
        - image: gcr.io/k8s-staging-gateway-api/echo-basic:v20231214-v1.0.0-140-gf544a46e
          imagePullPolicy: IfNotPresent
          name: backend
          ports:
            - containerPort: 3000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
  namespace: apk
spec:
  parentRefs:
    - name: wso2-apk-default
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: backend
          port: 3000
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /backend-path
          method: GET