# Copyright (c) 2022, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

{{- if .Values.wso2.apk.dp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.wso2.apk.dp.runtime.deployment.replicas }}
  strategy:
    type: {{ .Values.wso2.apk.dp.runtime.deployment.strategy }}
  selector:
    matchLabels:
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" .Values.wso2.apk.dp.runtime.appName ) | indent 6}}
  template:
    metadata:
      labels:
        networkPolicyId: {{ .Values.wso2.apk.dp.runtime.deployment.npi }}
{{ include "apk-helm.pod.selectorLabels" (dict "root" . "app" .Values.wso2.apk.dp.runtime.appName ) | indent 8}}
    spec:
      serviceAccountName: {{ .Values.wso2.apk.auth.serviceAccountName }}
      containers:
        - name: runtime-ds
          image: {{ .Values.wso2.apk.dp.runtime.deployment.image }}
          imagePullPolicy: {{ .Values.wso2.apk.dp.runtime.deployment.imagePullPolicy }}
          ports:
            - containerPort: 9443
              protocol: "TCP"
            - containerPort: 9444
              protocol: "TCP"
          readinessProbe:
            httpGet:
              path: /health
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: {{ .Values.wso2.apk.dp.runtime.deployment.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.apk.dp.runtime.deployment.readinessProbe.periodSeconds }}    
          livenessProbe:
            httpGet:
              path: /health
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: {{ .Values.wso2.apk.dp.runtime.deployment.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.apk.dp.runtime.deployment.livenessProbe.periodSeconds }}
{{ include "apk-helm.deployment.resources" .Values.wso2.apk.dp.runtime.deployment.resources | indent 10 }}
          volumeMounts:
            - mountPath: /home/wso2apk/runtime/security/wso2carbon.key
              name: runtime-signing-keystore-volume
              subPath: wso2carbon.key
            - mountPath: /home/wso2apk/runtime/security/mg.pem
              name: runtime-ds-jwt-validation-key-volume
              subPath: mg.pem
            - mountPath: /home/wso2apk/runtime/conf/Config.toml
              name: config-toml-volume
              subPath: Config.toml
            - mountPath: /home/wso2apk/runtime/security/controlplane.pem
              name: cp-public-key-volume
            {{ if and .Values.wso2.apk.dp.controlPlane .Values.wso2.apk.dp.controlPlane.tls }}
              subPath: {{ .Values.wso2.apk.dp.controlPlane.tls.fileName | default "tls.crt"}}
            {{ else }}
              subPath: tls.crt
            {{ end }}
            - name: runtime-ds-tls-volume
              mountPath: /home/wso2apk/runtime/security/runtime.key
            {{- if and .Values.wso2.apk.dp.runtime.configs .Values.wso2.apk.dp.runtime.configs.tls }}
              subPath: {{ .Values.wso2.apk.dp.runtime.configs.tls.certKeyFilename | default "tls.key" }}
            {{- else }}
              subPath: tls.key
            {{- end }}
            - name: runtime-ds-tls-volume
              mountPath: /home/wso2apk/runtime/security/runtime.pem
            {{- if and .Values.wso2.apk.dp.runtime.configs .Values.wso2.apk.dp.runtime.configs.tls }}
              subPath: {{ .Values.wso2.apk.dp.runtime.configs.tls.certFilename | default "tls.crt" }}
            {{- else }}
              subPath: tls.crt
            {{- end }}
      {{- if and .Values.wso2.subscription .Values.wso2.subscription.imagePullSecrets}}
      imagePullSecrets:
        - name: {{ .Values.wso2.subscription.imagePullSecrets }}
      {{- else if and .Values.wso2.subscription (not (eq .Values.wso2.subscription.username "")) (not (eq .Values.wso2.subscription.password "")) }}
      imagePullSecrets:
        - name: {{ template "apk-helm.resource.prefix" . }}-apk-wso2-private-registry-creds
      {{ end }}      

      volumes:
        - name: runtime-signing-keystore-volume
          secret: 
            secretName: {{ template "apk-helm.resource.prefix" . }}-signing-keystore-secret
        - name: runtime-ds-jwt-validation-key-volume
          secret: 
            secretName: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-jwt-validaion-secret
        - name: config-toml-volume
          configMap:
            name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-configmap
        - name: cp-public-key-volume
          secret:
       {{ if and .Values.wso2.apk.dp.controlPlane .Values.wso2.apk.dp.controlPlane.tls }}
            secretName: {{ .Values.wso2.apk.dp.controlPlane.tls.certificatesSecret | default (printf "%s-admin-server-cert" (include "apk-helm.resource.prefix" .)) }}
        {{ else }}
            secretName: {{ template "apk-helm.resource.prefix" . }}-admin-ds-server-cert
       {{ end }}
        - name: runtime-ds-tls-volume
          secret:
       {{ if and .Values.wso2.apk.dp.runtime.configs .Values.wso2.apk.dp.runtime.configs.tls }}
            secretName: {{ .Values.wso2.apk.dp.runtime.configs.tls.certificatesSecret | default (printf "%s-runtime-ds-server-cert" (include "apk-helm.resource.prefix" .)) }}
       {{ else }}
            secretName: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-server-cert
       {{ end }}
{{- end -}}
