# Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
{{- if .Values.wso2.apk.dp.enabled }}
apiVersion: "gateway.networking.k8s.io/v1beta1"
kind: "HTTPRoute"
metadata:
  name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-httproute
  namespace: {{ .Release.Namespace }}
  labels:
    api-name: "runtime-domain-service"
    api-version: "1.0.0"
spec:
  hostnames:
  - "{{ .Values.wso2.apk.listener.hostname | default "api.am.wso2.com"}}"
  rules:
  - matches:
    - path:
        type: "Exact"
        value: "/apis"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "Exact"
        value: "/apis"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/apis/(.*)"
      method: "PUT"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/apis/(.*)"
      method: "DELETE"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/apis/(.*)/generate-key"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "Exact"
        value: "/apis/import-service"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "Exact"
        value: "/apis/import-definition"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "Exact"
        value: "/apis/validate-definition"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "Exact"
        value: "/apis/validate"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/apis/(.*)/definition"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/apis/(.*)/definition"
      method: "PUT"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/apis/(.*)/endpoint-certificates"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/apis/(.*)/endpoint-certificates"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/apis/(.*)/endpoint-certificates/(.*)"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/apis/(.*)/endpoint-certificates/(.*)"
      method: "PUT"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/apis/(.*)/endpoint-certificates/(.*)"
      method: "DELETE"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "Exact"
        value: "/apis/export"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "Exact"
        value: "/apis/copy-api"
      method: "POST"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "Exact"
        value: "/services"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "PathPrefix"
        value: "/services"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/services/(.*)/usage"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "Exact"
        value: "/policies"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  - matches:
    - path:
        type: "RegularExpression"
        value: "/policies/(.*)"
      method: "GET"
    backendRefs:
    - group: dp.wso2.com
      kind: Backend
      name: {{ template "apk-helm.resource.prefix" . }}-runtime-ds-backend
  parentRefs:
  - group: "gateway.networking.k8s.io"
    kind: "Gateway"
    name: "default"
    sectionName: "httpslistener"
{{- end -}}
