name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  workflow_dispatch:
    inputs:
      patch:
        description: 'Patch the existing extension in VS Code Marketplace'
        type: boolean
        required: true
        default: false
      preRelease:
        description: 'Pre release the existing extension in VS Code Marketplace'
        type: boolean
        required: true
        default: false
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18.x'
        - run: cd runtime/runtime-ui/
        - run: yarn --frozen-lockfile
        - run: npm install --global vsce
        - name: "Patch the pre released extension in VS Code Marketplace"
          if: ${{ github.event.inputs.patch == 'true' && github.event.inputs.preRelease == 'true' }}
          run: vsce publish patch --pre-release -p ${{ secrets.VSCE_TOKEN }}
        - name: "Pre release in VS Code Marketplace"
          if: ${{ github.event.inputs.patch == 'false' && github.event.inputs.preRelease == 'true' }}
          run: vsce publish --pre-release -p ${{ secrets.VSCE_TOKEN }}
        - name: "Release the extension in VS Code Marketplace"
          if: ${{ github.event.inputs.patch == 'false' && github.event.inputs.preRelease == 'false' }}
          run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
        - name: "Patch the released version in VS Code Marketplace"
          if: ${{ github.event.inputs.patch == 'true' && github.event.inputs.preRelease == 'false' }}
          run: vsce publish patch -p ${{ secrets.VSCE_TOKEN }}


