name: Lint YAML and Bash files

on:
  workflow_dispatch:
  pull_request_target:
    types: [labeled]
concurrency: 
  group: yaml-lint-${{ github.event.number || github.run_id }}
  cancel-in-progress: true
env:
  GH_TOKEN: ${{ secrets.APK_BOT_TOKEN }}

jobs:
  lint:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request_target' && contains(github.event.label.name, 'trigger-action'))
    name: Lint Code Base
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_YAML: true
          FILTER_REGEX_INCLUDE: helm-charts/crds/.*\.ya?ml$
